### ISSUE TITLE
Select does not close DateRangePicker

### ISSUE THREAD

**Issue by dborstelmann** [mui-org/material-ui-pickers#2170] opened 2021-02-07 00:37 UTC
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-pickers/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

DateRangePicker does not close when you select start and end.

## Expected Behavior 🤔

DateRangePicker should close when you select start and end.

## Steps to Reproduce 🕹

https://codesandbox.io/s/stupefied-waterfall-9md45?fontsize=14&hidenavigation=1&theme=dark

Steps:

1. Click start
2. Select a date
3. Select a later end date
4. Notice picker does not close

## Your Environment 🌎

React app with material v5 (also saw this on v4).

| Tech        | Version |
| ----------- | ------- |
| @material-ui/core | v5.0.0-alpha.24  |
| React                      | 16.3                     |
| Browser                  | Chrome (Mac)    |
| TypeScript              | Yes                      |

**Comment by oliviertassinari** [comment] 2021-02-07 22:55
Duplicate of https://github.com/mui-org/material-ui/issues/24828

**Closed as completed by oliviertassinari** 2021-02-07 22:55 UTC
Labels: status: needs triage
