### ISSUE TITLE
Suggestion on time picker 

### ISSUE THREAD

**Issue by ghost** [mui-org/material-ui-pickers#1880] opened 2020-06-10 17:45 UTC
**Is your feature request related to a problem? Please describe.**

Although your current time picker (the one where the clock is painted and you click arrows) might seem pretty, I'd say it can be a bit not intuitive for some users to use (especially non computer savvy ones).

**Describe the solution you'd like**

I'd suggest just as an alternative to also additionally provide other kinds of time pickers, like this for example:

![Capture](https://user-images.githubusercontent.com/41240312/84300579-83d35a80-ab63-11ea-980f-a8b9f2be267e.PNG)

Although it may not look as pretty as your approach, I think you would agree it is much easier and straightforward for users to use and grasp.

**Comment by oliviertassinari** [comment] 2020-06-15 11:14
Duplicate of #1860

**Closed as completed by oliviertassinari** 2020-06-15 11:14 UTC
Labels: duplicate, component: TimePicker
