### ISSUE TITLE
How to access `ref` from KeyboardDatePicker ? or how to change keyboard focus to this input?

### ISSUE THREAD

**Issue by mdennyh** [mui-org/material-ui-pickers#1591] opened 2020-03-19 04:07 UTC
I try change the page focus to a single Datepicker component from material-ui (https://material-ui-pickers.dev/api/KeyboardDatePicker). 

There, they clearly stated that any `ref` props will be forwarded to `root` component (whatever it is). So I assume it will behave like any typical input. But any attempt to access `ref` will throw an error: `Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?`

    // THIS DOESN'T WORKS
    <KeyboardDatePicker``
       clearable
       ref={this.inputs.birth_date} 
       value={this.state.birth_date}
       onChange={this.handleChangeDate}
    /> 

    // THIS WORKS
    <input ref={this.inputs.birth_date} />`

**Comment by oliviertassinari** [comment] 2020-03-19 10:19
Duplicate of #1303

**Closed as completed by oliviertassinari** 2020-03-19 10:19 UTC
Labels: duplicate
