### ISSUE TITLE
checkPropTypes.js?a15c:20 Warning: Failed prop type: Invalid prop `TextFieldComponent` supplied to `DateTextField`.

### ISSUE THREAD

**Issue by vijayreddyalavala** [mui-org/material-ui-pickers#1157] opened 2019-07-03 07:31 UTC
I'm seeing a warning in the console. I am trying to use Datepicker component and want to clear all warning. This is the warning I'm getting.

Warning: Failed prop type: Invalid prop `TextFieldComponent` supplied to `DateTextField`.
    in DateTextField (created by Context.Consumer)
    in WithUtils(DateTextField) (created by ModalWrapper)
    in ModalWrapper (created by BasePicker)
    in BasePicker (created by Context.Consumer)
    in WithUtils(BasePicker) (created by DatePickerModal)
    in DatePickerModal (created by ForwardRef)
    in ForwardRef (created by PickADate)
    in MuiPickersUtilsProvider (created by PickADate)
    in PickADate (created by Context.Consumer)
    in div (created by ForwardRef(Grid))
    in ForwardRef(Grid) (created by WithStyles(ForwardRef(Grid)))
    in WithStyles(ForwardRef(Grid)) (created by Layout)
    in div (created by ForwardRef(Grid))
    in ForwardRef(Grid) (created by WithStyles(ForwardRef(Grid)))
    in WithStyles(ForwardRef(Grid)) (created by Layout)
    in Layout (created by Context.Consumer)
    in Route (created by PrivateRoute)
    in PrivateRoute
    in Switch
    in Route (created by App)
    in Router (created by App)
    in div (created by App)
    in App (created by Connect(App))
    in Connect(App)
    in ThemeProvider
    in CssBaseline
    in Provider

-------------------------------------
Please check the code below

import React from 'react';
import { MuiPickersUtilsProvider, DatePicker } from 'material-ui-pickers';
import DateFnsUtils from '@date-io/date-fns';

const onChangeMethod = () => {
  console.log('On change method is called!');
};

const PickADate = () => (

  <MuiPickersUtilsProvider utils={DateFnsUtils}>
    <div>This is a date picker </div>
    <DatePicker onChange={onChangeMethod}>  </DatePicker>

  </MuiPickersUtilsProvider>

);

export default PickADate;

**Comment by vijayreddyalavala** [comment] 2019-07-03 07:43
Looking at the code we can understand that I am not writing DateTextField or its property TextFieldComponent anywhere in my code. It looks like this component is being rendered as it is invoked by another component. It is like a parent-child component tree and at some point, the DateTextField component is involved and it is being passed an invalid prop

**Comment by dmtrKovalenko** [comment] 2019-07-03 09:12
Duplicate of #1086

**Closed by dmtrKovalenko** 2019-07-03 09:12 UTC

**Comment by attila-bulenda** [comment] 2020-05-29 08:20
I get the same error message and it seems that there is no real solution anywhere. This thread has been closed as duplicate, but the other referred issue does not provide any solution either. Do you think we could have some follow up, or a piece of advice? Thanks in advance.

**Comment by oliviertassinari** [comment] 2020-05-29 08:23
@Zumwaloro We have no plan to solve the problem. You can upgrade to v4.0.0-alpha.7, we have addressed the issue with a new API.

**Comment by attila-bulenda** [comment] 2020-05-29 09:07
Ok, thanks!
