### ISSUE TITLE
Allow customizing the month format in MonthSelection

### ISSUE THREAD

**Issue by tpeek** [mui-org/material-ui-pickers#2161] opened 2020-11-22 03:30 UTC
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-pickers/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

The `monthText` variable in the MonthSelection component is hard coded as `'monthShort'`.

https://github.com/mui-org/material-ui-pickers/blob/next/lib/src/views/Calendar/MonthSelection.tsx#L74

![Screen Shot 2020-11-21 at 7 18 55 PM](https://user-images.githubusercontent.com/7531241/99892882-dc3c7700-2c2e-11eb-9505-3214e743fbe8.png)

It would be great if this was customizable, so that the full month name could be displayed.

## Motivation 🔦

Our designs call for the full month name to be displayed.

**Comment by oliviertassinari** [comment] 2020-11-22 10:56
Duplicate of https://github.com/mui-org/material-ui/issues/23524

**Closed as completed by oliviertassinari** 2020-11-22 10:56 UTC
Labels: status: needs triage
