### ISSUE TITLE
Unstable_TrapFocus.js is causing Maximum call stack size exceeded. (4.0.0-alpha.10)

### ISSUE THREAD

**Issue by callmeberzerker** [mui-org/material-ui-pickers#2033] opened 2020-07-25 10:37 UTC
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-pickers/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

I have:

*  "@material-ui/core": "4.11.0", (upgraded from 4.10.0)
*  "@material-ui/pickers": "4.0.0-alpha.10", (upgraded from 4.0.0-alpha.5)

After fixing the adaptations with props in pickers (autoOk, invalidDate, error removal etc), I saw that while my FormComponent wrapper works OK in a normal page -> but it causes the maximum call stack size exceeded if the form control is displayed in a `ModalDialog` from material-ui and results with fast open/closing of the Popover from the DatePicker.

I also noticed that if I put a debug point in `Unstable_TrapFocus.js` at the line that's causing the infinite calls, the `DatePicker` Popover display properly. (debug point on `rootRef.current.focus();`)

```
      if (rootRef.current && !rootRef.current.contains(doc.activeElement)) {
        rootRef.current.focus();
      }
```

## Expected Behavior 🤔

The DatePicker popover should not cause maximum call stack size exceeded and should display. :)

## Steps to Reproduce 🕹

I will try to create a sample codesandbox issue later.

## Context 🔦

```
Unstable_TrapFocus.js:77 Uncaught RangeError: Maximum call stack size exceeded.
    at HTMLDocument.contain (Unstable_TrapFocus.js:77)
    at HTMLDocument.contain (Unstable_TrapFocus.js:77)
    at HTMLDocument.contain (Unstable_TrapFocus.js:77)
    at HTMLDocument.contain (Unstable_TrapFocus.js:77)
    at HTMLDocument.contain (Unstable_TrapFocus.js:77)
    at HTMLDocument.contain (Unstable_TrapFocus.js:77)
    at HTMLDocument.contain (Unstable_TrapFocus.js:77)
    at HTMLDocument.contain (Unstable_TrapFocus.js:77)
    at HTMLDocument.contain (Unstable_TrapFocus.js:77)
    at HTMLDocument.contain (Unstable_TrapFocus.js:77)
    at HTMLDocument.contain (Unstable_TrapFocus.js:77)
    at HTMLDocument.contain (Unstable_TrapFocus.js:77)
    at HTMLDocument.contain (Unstable_TrapFocus.js:77)
    at HTMLDocument.contain (Unstable_TrapFocus.js:77)
    at HTMLDocument.contain (Unstable_TrapFocus.js:77)
    at HTMLDocument.contain (Unstable_TrapFocus.js:77)
    at HTMLDocument.contain (Unstable_TrapFocus.js:77)
    at HTMLDocument.contain (Unstable_TrapFocus.js:77)
    at HTMLDocument.contain (Unstable_TrapFocus.js:77)
    at HTMLDocument.contain (Unstable_TrapFocus.js:77)
    at HTMLDocument.contain (Unstable_TrapFocus.js:77)
    at HTMLDocument.contain (Unstable_TrapFocus.js:77)
    at HTMLDocument.contain (Unstable_TrapFocus.js:77)
    at HTMLDocument.contain (Unstable_TrapFocus.js:77)
    at HTMLDocument.contain (Unstable_TrapFocus.js:77)
    at HTMLDocument.contain (Unstable_TrapFocus.js:77)
    at HTMLDocument.contain (Unstable_TrapFocus.js:77)
    at HTMLDocument.contain (Unstable_TrapFocus.js:77)
    at HTMLDocument.contain (Unstable_TrapFocus.js:77)
    at HTMLDocument.contain (Unstable_TrapFocus.js:77)
    at HTMLDocument.contain (Unstable_TrapFocus.js:77)
    at HTMLDocument.contain (Unstable_TrapFocus.js:77)
    at HTMLDocument.contain (Unstable_TrapFocus.js:77)
    at HTMLDocument.contain (Unstable_TrapFocus.js:77)
    at HTMLDocument.contain (Unstable_TrapFocus.js:77)
    at HTMLDocument.contain (Unstable_TrapFocus.js:77)
    at HTMLDocument.contain (Unstable_TrapFocus.js:77)
    at HTMLDocument.contain (Unstable_TrapFocus.js:77)
    at HTMLDocument.contain (Unstable_TrapFocus.js:77)
    at HTMLDocument.contain (Unstable_TrapFocus.js:77)
    at HTMLDocument.contain (Unstable_TrapFocus.js:77)
    at HTMLDocument.contain (Unstable_TrapFocus.js:77)
    at Day.tsx:174
    at commitHookEffectListMount (react-dom.development.js:19731)
    at commitPassiveHookEffects (react-dom.development.js:19769)
    at HTMLUnknownElement.callCallback (react-dom.development.js:188)
    at HTMLUnknownElement.dispatchEvent (<anonymous>)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:237)
    at invokeGuardedCallback (react-dom.development.js:292)
    at flushPassiveEffectsImpl (react-dom.development.js:22853)
```

**Comment by oliviertassinari** [comment] 2020-07-25 10:39
Duplicate of #1852

**Closed as completed by oliviertassinari** 2020-07-25 10:39 UTC
Labels: duplicate
