### ISSUE TITLE
Clock dial hiding in safari browser upon selecting hours in time picker

### ISSUE THREAD

**Issue by anking** [mui-org/material-ui-pickers#1457] opened 2020-01-17 19:19 UTC
We've noticed a weird TimePicker & Date&Time Picker behavior in safari browser on Mac:
When the component first renders and you select hours component will display a minute dial that instantly hides away, but re-appeares if you click on it or click on any other control:
![image](https://user-images.githubusercontent.com/9019734/72639780-62fc3580-3934-11ea-9425-336ab280552c.png)

if can be reproduced here:
https://material-ui-pickers.dev/demo/timepicker

**Comment by dmtrKovalenko** [comment] 2020-01-17 19:31
Duplicate of #1405

**Closed as completed by dmtrKovalenko** 2020-01-17 19:31 UTC
