### ISSUE TITLE
Cant show changing time

### ISSUE THREAD

**Issue by leonidkuznetsov18** [mui-org/material-ui-pickers#1326] opened 2019-09-24 17:31 UTC
For DateTimePicker in props `minDate` added date with time `moment().add(2, "h").toDate().getTime()` , but dont see any updates for time, but if I change day,year or month it works perfect. My format `MM/DD/YYYY h:m A`

**Comment by dmtrKovalenko** [comment] 2019-09-25 10:01
Yeah timepicker is not supportting time ranges or disabled time. Duplicate of #519

**Closed as completed by dmtrKovalenko** 2019-09-25 10:01 UTC
