### ISSUE TITLE
KeyboardDatePicker set minDate with value null sets the value to minDate by default

### ISSUE THREAD

**Issue by karthickshanmugam0689** [mui-org/material-ui-pickers#1493] opened 2020-02-05 17:17 UTC
Material-UI KeyboardDatePicker is unable to prevent the date selection on setting minDate.

Material-UI KeyboardDatePicker with autoOK and variant="inline" couldn't prevent setting value to minDate when value is null and minDate is set to date greater than today

## Environment
"@material-ui/core": "4.3.1",
"@material-ui/icons": "3.0.2",
"@material-ui/pickers": "3.2.2",
"@material-ui/styles": "4.3.0",

## Steps to reproduce
1. Use KeyboardDatePicker with autoOK and variant='inline'
2. Set value to null 
3. Set minDate to future date => a date greater than today
4. On click of calendar icon in KeyboardDatePicker, by default value is set to minDate and onChange function call is triggered
5. This problem is not occuring when setting minDate to a date less than today

Example React Component for the same
<KeyboardDatePicker
autoOk={true}
variant="inline"
minDate={minDate}
value={value ? value : null}
onChange={handeChange}
/>

Example with minDate less than today:
https://codesandbox.io/s/sparkling-cloud-2zxtk

Example with minDate greater than today:
https://codesandbox.io/s/intelligent-goodall-o7cxy

**Comment by dmtrKovalenko** [comment] 2020-02-06 20:44
Duplicate of #1491

**Closed as completed by dmtrKovalenko** 2020-02-06 20:44 UTC
