### ISSUE TITLE
openView indicator in clock view

### ISSUE THREAD

**Issue by ph-fritsche** [mui-org/material-ui-pickers#1926] opened 2020-06-23 10:38 UTC
**Is your feature request related to a problem? Please describe.**
You have no indicator if you selected the minutes part and are on seconds view.
This is especially confusing when you click the preselected time or the seconds part equals your selected or preselected minutes part.

For hours/minutes the user can interpret the scale (less than ideal) or (on mobile) the toolbar highlight, but minutes and seconds are displayed the same.
Displaying AM/PM on minutes and seconds view adds to the confusion.

**Describe the solution you'd like**
Some indicator what the clock view is displaying (e.g. "Hour"/"Minute"/"Second" above or even better inside ("h"/"min"/"sec"?) the clock.
Hide AM/PM on minutes and seconds.

**Describe alternatives you've considered**
Replacing the ToolbarComponent.

**Comment by dmtrKovalenko** [comment] 2020-07-01 14:06
![image](https://user-images.githubusercontent.com/16926049/86253351-1bedbe00-bbbd-11ea-88ff-aee07866da15.png)

Doesn't it work for you?

**Comment by oliviertassinari** [comment] 2020-07-01 16:58
From what I understand, the issue is with the desktop version only. Shouldn't we close as a duplicate of #1860?

**Comment by dmtrKovalenko** [comment] 2020-07-02 08:56
No, it is not the duplicate. It is about missing arrows. 

I think it should be just closed.

**Comment by oliviertassinari** [comment] 2020-07-02 09:04
@dmtrKovalenko I believe the issue about the missing context. From what I understand arrows won't solve the issue. It works on mobile because the current "segment" is highlighted:

<img width="301" alt="Capture d’écran 2020-07-02 à 11 03 21" src="https://user-images.githubusercontent.com/3165635/86339332-c0224400-bc53-11ea-91dc-6f0a6f25bbe1.png">

**Comment by ph-fritsche** [comment] 2020-07-02 10:09
Yes, it's about missing context. When testing multiple configurations this view was not obvious to some and led to multiple clicks as the user was figuring out what to do.

Is this minutes? If you know the control you will guess it quickly, but if you don't it lets the user pause for a moment.
![grafik](https://user-images.githubusercontent.com/39068198/86344712-e1d2f980-bc5a-11ea-913a-1bb2667fa36f.png)

I think this would be far more obvious:
![grafik](https://user-images.githubusercontent.com/39068198/86346083-b2bd8780-bc5c-11ea-950b-16cef091d1b8.png)

**Comment by ph-fritsche** [comment] 2020-07-02 10:19
As for the mobile picker the highlight helps, but
* Seconds are not part of the default toolbar when using `DateTime` with `seconds`
* The highlight is not not as easy to spot for those with impaired (color) vision
* When the user clicks for going from '07:**30**:30' to '07:30:**30**' it is not as obvious as it could be that the component noticed the click and moved on. Therefore the user clicks again. If he wanted to change '07:30:30' to let's say '07:30:45' this repeated click for minutes finishes and closes the control so that he has to reopen it.

**Comment by oliviertassinari** [comment] 2020-07-02 10:24
@ph-fritsche Alright, awesome, thanks for the extra context, let's solve this problem by removing the clock view on desktop: #1860.

**Closed as completed by oliviertassinari** 2020-07-02 10:24 UTC
Labels: component: TimePicker
