### ISSUE TITLE
Navigating rapidly between months causes Calendar to be in a broken state with no visible header or days.

### ISSUE THREAD

**Issue by mtanfield** [mui-org/material-ui-pickers#998] opened 2019-04-19 19:58 UTC
## Environment

| Tech                | Version |
|---------------------|---------|
| material-ui-pickers | 3.0.0-alpha.1 |
| material-ui         | 4.0.0-alpha.7 |
| React               | 16.8.6 |
| Browser             | Chrome 73.0 |
| Peer library        | date-fns 2.0.0-alpha.21 and @date-io/date-fns 1.1.0 |

## Steps to reproduce
1. Open Date Picker.
2. Navigate to beginning or end of month with keyboard.
3. Rapidly move the selection to/from the next/previous month with keyboard.

## Expected behavior
Next/Previous month displays normally.

## Actual behavior
Calendar header and days do not display in next/previous month.

## Live example
https://codesandbox.io/s/lrmpkl387z

The code is the same as the sandbox, just with updated dependencies (and the addition of the ThemeProvider, which was required with the updates).

This also occurs with the examples on the website:
https://next.material-ui-pickers.dev/api/datepicker

**Comment by dmtrKovalenko** [comment] 2019-04-20 11:56
Can you plz link the video or gif how to reproduce it?
Thank you

**Comment by mike-tanfield-nano** [comment] 2019-04-22 16:16
![Material UI Pickers Issue](https://user-images.githubusercontent.com/46762700/56510644-00ceeb00-64f0-11e9-8a27-5fd196af925b.gif)

**Comment by mtanfield** [comment] 2019-04-22 16:18
![Material UI Pickers Issue](https://user-images.githubusercontent.com/26603163/56510749-602cfb00-64f0-11e9-8b65-30a14889e882.gif)

**Comment by dmtrKovalenko** [comment] 2019-04-23 09:39
Oookey, that seems to be an issue in react-transition-group

**Comment by dmtrKovalenko** [comment] 2019-06-16 18:37
Fixed in v3.1.1

**Closed by dmtrKovalenko** 2019-06-16 18:37 UTC
Labels: 🐛 bug
