### ISSUE TITLE
Adapter re-export problem

### ISSUE THREAD

**Issue by Vincz** [mui-org/material-ui-pickers#1630] opened 2020-04-09 12:16 UTC
![A GIF or MEME to give some spice of the internet](url)

## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |  4.0.0-alpha5       |
| material-ui          |   4.9.9      |

If I try to import the adapter as describe in the documentation:
`import DateFnsUtils from '@material-ui/pickers/adapter/date-fns';`

I get the following error : 
```
SyntaxError: Unexpected token 'export'
    at Module._compile (internal/modules/cjs/loader.js:891:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at eval (webpack:///external_%22@material-ui/pickers/adapter/date-fns%22?:1:18)
```

If I import directly from the lib, it works:
`import DateFnsUtils from '@date-io/date-fns';`

Is there a special babel config in order to make it works  ?

**Comment by oliviertassinari** [comment] 2020-04-09 12:20
Duplicate of #1627

**Closed as completed by oliviertassinari** 2020-04-09 12:20 UTC
Labels: duplicate
