### ISSUE TITLE
TimePicker displays AM even if not requested

### ISSUE THREAD

**Issue by mbrucher** [mui-org/material-ui-pickers#1187] opened 2019-07-17 09:21 UTC
## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |   3.2.0      |
| material-ui          |  4.2.0       |
| React                |   16.8      |
| Browser              |         |
| Peer library         |   moment      |  |

## Steps to reproduce

I used this code:
```
        <TimePicker
          ampm={false}
          className={classes.nested}
          onChange={this.handleChange}
          name="duration"
          type="time"
          id="duration"
          value={value}
          label={<FormattedMessage id="DurationItem.title" defaultMessage="For" />}
          minutesStep={5}
          InputProps={{
            endAdornment: (
              <InputAdornment position="end">
                <TimelapseIcon />
              </InputAdornment>
            ),
          }}
        />
```

## Expected behavior

I should not see AM or PM in the Time picker

## Actual behavior

I see AM.

## Live example

https://weweave.org/nearby and click on the pen icon on the map. The Duration should be 00:30 and not 12:30 AM.

Also oddly even on a French localized browser, the DateTimePicker displays UK/US date time!

**Comment by dmtrKovalenko** [comment] 2019-07-29 14:51
Cannot reproduce it. Please provide codesandbox if you are thinking this issue is still valid

**Comment by mbrucher** [comment] 2019-08-02 09:32
I used the example from https://material-ui.com/components/pickers/, edited it on codesandbox, added ampm={false} and it's not working.
Use a british-localized Chrome.

**Comment by mbrucher** [comment] 2019-08-07 16:22
Did you manage to reproduce it with these parameters?

**Comment by Aleksis92** [comment] 2019-12-04 10:23
What about this? Take this bug on Chrome. IE 11 - fine

**Comment by dmtrKovalenko** [comment] 2020-02-23 12:27
Should be fixed in v4

**Closed by dmtrKovalenko** 2020-02-23 12:27 UTC

**Comment by mbrucher** [comment] 2020-02-23 13:41
Great thanks!
