### ISSUE TITLE
TypeScript error  with v4.0.0-alpha.10

### ISSUE THREAD

**Issue by stunaz** [mui-org/material-ui-pickers#1861] opened 2020-06-05 02:14 UTC
## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |    next     |
| material-ui          |   latest      |
| TypeScript           |  latest       |
| React                |    latest     |
| Peer library         |    dayjs latest     |  |

## Steps to reproduce

https://codesandbox.io/s/recursing-engelbart-wy2ub?file=/src/App.tsx

## Expected behavior

No error

## Actual behavior

```typescript
(JSX attribute) BasePickerProps<unknown, unknown>.onChange: (date: unknown, keyboardInputValue?: string | undefined) => void
onChange callback @DateIOType.

Type '(date: dayjs.Dayjs | null, keyboardInputValue?: string | undefined) => void' is not assignable to type '(date: unknown, keyboardInputValue?: string | undefined) => void'.
  Types of parameters 'date' and 'date' are incompatible.
    Type 'unknown' is not assignable to type 'Dayjs | null'.
      Type 'unknown' is not assignable to type 'Dayjs'.ts(2322)
```

Its left to fix this comment: https://github.com/mui-org/material-ui-pickers/issues/1861#issuecomment-658541026

**Comment by oliviertassinari** [comment] 2020-06-15 11:07
@stunaz Any idea on how we can solve this problem?

**Comment by ryoshi1986** [comment] 2020-06-19 09:05
We could change "DateTimePicker.d.ts" and so on like this (at least this works for me to get rid of the error ^__^):
**From:**
```ts
export declare const DateTimePicker: import("react").ForwardRefExoticComponent<BaseDateTimePickerProps & import("..").BasePickerProps<unknown, unknown>
```

**To:**
```ts
export declare const DateTimePicker: import("react").ForwardRefExoticComponent<BaseDateTimePickerProps & import("..").BasePickerProps<unknown, MaterialUiPickersDate | null>[...]
```

It´s correctly defined in 'BasePicker.d.ts' but get´s overwritten with <unknown, unknown> I guess.

**Comment by dmtrKovalenko** [comment] 2020-06-28 08:46
What are you using for your build system? `tsc` or `babel`? What version of typescript do you have?

**Comment by ryoshi1986** [comment] 2020-06-29 07:22
tsc: 3.9.5
TS: 3.9.5

**Comment by dmtrKovalenko** [comment] 2020-07-10 19:16
Fixed in v4-alpha.9  🎉

**Comment by stunaz** [comment] 2020-07-15 04:38
yeah.... fixed in v4-alpha.9 ... but introduced many more bugs typescript related... the interference doesn't work... 
- `onMonthChange` value is not interfered as onChange
- `renderDay` day is not interfered as onChange

**Comment by oliviertassinari** [comment] 2020-07-15 10:29
@stunaz If you could open a new issue with a reproduction, it would be awesome, it will help us fix the problem or at least improve the documentation or the TypeScript test cases.

**Closed as completed** 2021-07-07 12:09 UTC
Labels: bug 🐛, typescript
