### ISSUE TITLE
Fade does not export.

### ISSUE THREAD

**Issue by BerkayAkgurgen** [mui-org/material-ui-pickers#2201] opened 2021-07-12 10:34 UTC
The codes shown below were taken from the official site, but I am getting an export problem. Error:
"./node_modules/@material-ui/pickers/esm/makePickerWithState-5a79cb8a.js
Attempted import error: 'fade' is not exported from '@material-ui/core/styles'."
```
import React, { useState } from 'react';
import Box from '@material-ui/core/Box';
import { useStyles } from 'useStyles/userFilterPopupStyle'
import DateFnsUtils from '@date-io/date-fns'; // choose your lib
import {
    DatePicker,
    TimePicker,
    DateTimePicker,
    MuiPickersUtilsProvider,
} from '@material-ui/pickers';

const UserFilterDate = () => {
    const [selectedDate, handleDateChange] = useState(new Date());
    const classes = useStyles();

    return (
        <MuiPickersUtilsProvider utils={DateFnsUtils}>
            <DatePicker value={selectedDate} onChange={handleDateChange} />
            <TimePicker value={selectedDate} onChange={handleDateChange} />
            <DateTimePicker value={selectedDate} onChange={handleDateChange} />
        </MuiPickersUtilsProvider>
    )
}

export default UserFilterDate
```

**Comment by oliviertassinari** [comment] 2021-07-12 10:40
Duplicate of #2200

**Closed as completed by oliviertassinari** 2021-07-12 10:40 UTC
Labels: duplicate

**Comment by BerkayAkgurgen** [comment] 2021-07-12 11:50
> 
> 
> Duplicate of #2200

In this case, ı get "makeStyles" export error.
