### ISSUE TITLE
Week number

### ISSUE THREAD

**Issue by dvh91** [mui-org/material-ui-pickers#1973] opened 2020-07-11 14:42 UTC
There's a need, mostly in analytics products, to have a date range picker with the context of week number.
From what I've seen and tried both in v3 and v4 alphas, I can't modify the `Calendar` using the existing API in a way that will allow me to add this feature to the calendar.

Is this something that you can consider in coming v4 as a feature or API change that will allow us to change it from the outside?

**Comment by oliviertassinari** [comment] 2020-07-11 14:57
Duplicate of #521

**Closed as completed by oliviertassinari** 2020-07-11 14:57 UTC
Labels: duplicate
