### ISSUE TITLE
Display week numbers

### ISSUE THREAD

**Issue by dmtrKovalenko** [mui-org/material-ui-pickers#1611] opened 2020-03-30 08:34 UTC
Got a feature request to be able display week numbers in calendar.

**Comment by HolgerWeber** [comment] 2020-03-30 09:01
![pickerWithWeeks](https://user-images.githubusercontent.com/17291425/77894507-aa2c6e00-7275-11ea-89da-fb54ffb3c54e.png)
We really would appreciate to have it similar like this.
Thanks

**Comment by oliviertassinari** [comment] 2020-03-30 15:05
@dmtrKovalenko I'm happy to see you changed your mind 👍 (#521), I was proposing this API in https://github.com/mui-org/material-ui-pickers/issues/1293#issuecomment-538374383:

```js
  /**
   * If `true`, a column is added to show the week numbers of the year.
   *
   * default false
   */
  showWeekNumbers: PropTypes.bool,
```

**Comment by oliviertassinari** [comment] 2020-04-12 15:08
Duplicate of #521

**Closed as completed by oliviertassinari** 2020-04-12 15:08 UTC
Labels: duplicate
