### ISSUE TITLE
Getting Change Event from MaterialUI Date Picker

### ISSUE THREAD

**Issue by shellac85** [mui-org/material-ui-pickers#1728] opened 2020-04-30 15:18 UTC
Will there be any way to get both the date as a string and the change event from Materui's Date Picker. Any help appreciated.

I am looking to call this method on the onChange from the DatePicker:

`  onChangeFrom: (event: React.ChangeEvent<{ name?: string; value: unknown }>) => void;`

And this is the code for the DatePicker:

`   <MuiPickersUtilsProvider utils={MomentUtils}>
    <DatePicker
      value={selectedDate}
      onChange={
        (date) => onChangeFrom(date)}
      }
    />
    </MuiPickersUtilsProvider>`

**Comment by dmtrKovalenko** [comment] 2020-05-01 10:24
In v4: You can pass an `onChange` right to `TextField` in `renderInput` (but make sure you are not overriding pickers logic). 

For the other types of submission, like button click, enter click or just finishing selection in the last date with `autoOk` we cannot provide an event, because it will be too generic (duplicate of #473)

**Closed as completed by dmtrKovalenko** 2020-05-01 10:24 UTC

**Comment by shellac85** [comment] 2020-05-01 10:36
Thanks. when will v4 be released?

**Comment by dmtrKovalenko** [comment] 2020-05-01 10:38
We are planning stable release in Q4 2020. But we are going to make `beta` really soon, which should not include anymore breaking changes. So it should be good to update.

**Comment by shellac85** [comment] 2020-05-01 10:38
Ok Thanks. I will check back then.
