### ISSUE TITLE
Respect if date value is set as null

### ISSUE THREAD

**Issue by TheLogan** [mui-org/material-ui-pickers#1204] opened 2019-07-25 14:44 UTC
![A GIF or MEME to give some spice of the  internet](https://media.giphy.com/media/KHJw9NRFDMom487qyo/giphy.gif)

**Is your feature request related to a problem? Please describe.**
I'm setting up a page for filtering content on my site, and filtering by day is pretty obvious and easy. However then I want to stop filtering by date, as such set the value of the datepicker to null, and it just sets the value to today instead, but that doesn't work as today is also a filterable value.

**Describe the solution you'd like**
Have the datepicker support no day having been selected.

**Describe alternatives you've considered**
Unmounting and hiding the datepicker, and have the user actually mount it when they want to set a date, and then unmounting it again if they want to clear the date, but this seems overkill.

**Additional context**
I am using an inline datepicker with only specific dates viable (days where content is actually available) I don't know if that makes any difference.

![image](https://user-images.githubusercontent.com/759433/61883188-3d005600-aefa-11e9-96ef-3151df9646c1.png)
As you can see there isn't even any content on today (the 25th), and yet it's still highlighted.

This issue seems to be related, though not a feature request as far as I can see.
#https://github.com/mui-org/material-ui-pickers/issues/774

**Comment by dmtrKovalenko** [comment] 2019-07-27 06:34
You can pass an `undefined`. This will render something like `Unknown` in the text field

**Comment by TheLogan** [comment] 2019-07-29 08:57
I tried it, it didn't change anything, but then, there isn't a text field, as I'm using an inline calendar.

**Comment by dmtrKovalenko** [comment] 2019-08-19 12:37
Sorry for long response. This is something for the next major version. Because of breaking changee

**Comment by mariotacke** [comment] 2020-02-06 21:44
I'm interested in this feature as well. A lot of my dates are optional and I would like to fully clear the picker box. passing `clearable` as an attribute and clicking it invokes the `onChange` function with `null`, but the picker still shows today's date.

**Comment by kerosan** [comment] 2020-05-25 10:42
not only `null` , `undefined` too

**Comment by dmtrKovalenko** [comment] 2020-05-25 10:43
@kerosan  We don't support `undefined`. `undefined` will be treated as unparsed value, so it will be like `new Date(undefined)` === `new Date()`

**Comment by oliviertassinari** [comment] 2020-05-25 11:13
+1 for leaving `undefined` out of the equation. This will be helpful to be consistent with the core and if we want to support a default value (uncontrolled). See [`useControlled.js`](https://github.com/mui-org/material-ui/blob/3443d2ce16f3280318a163a45faff8ba86f45903/packages/material-ui/src/utils/useControlled.js).

**Comment by dmtrKovalenko** [comment] 2020-05-25 11:15
This PR was closed by #1770 
Originally duplicate of #1613

**Closed by dmtrKovalenko** 2020-05-25 11:15 UTC
Labels: bug 🐛
