### ISSUE TITLE
how to avoid insert the same style

### ISSUE THREAD

**Issue by zhu1033527427** [mui-org/material-ui-pickers#1259] opened 2019-08-16 07:33 UTC
When @material-ui/pickers and @material-ui/core/Select in a same page，it will insert the same css，then they will be affected by each other，how to insert the style only once time!

![](http://lingshoutong.oss-cn-hangzhou.aliyuncs.com/lily/WX20190816-152028@2x.png)

![](http://lingshoutong.oss-cn-hangzhou.aliyuncs.com/lily/WX20190816-152304@2x.png)

**Comment by dmtrKovalenko** [comment] 2019-08-16 07:35
Duplicate of #1143

**Closed** 2019-08-19 12:34 UTC
