### ISSUE TITLE
Use onAccept, but not onChange

### ISSUE THREAD

**Issue by DrewBe121212** [mui-org/material-ui-pickers#1094] opened 2019-06-07 14:46 UTC
## Environment
| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |3.1.0|
| material-ui          |4.0.2|
| React                |16.8.6|
| Browser              |Chrome|
| Peer library         |moment|  |

## Steps to reproduce
1. Set the onAccept prop
2. remove/do not include the onChange prop

## Expected behavior
1. Date Picker is updated with selection

## Actual behavior
1. Error message is thrown: `material-ui-pickers.esm.js:2400 Uncaught TypeError: props.onChange is not a function
    at onChange (material-ui-pickers.esm.js:2400)
    at Object.onChange (material-ui-pickers.esm.js:1216)
    at Calendar._this.onDateSelect (material-ui-pickers.esm.js:698)
    at material-ui-pickers.esm.js:409`

I can fix it by passing onChange={() => null}, however this seems like an issue in the cases where we only want to update our local state when it is truly accepted. 

```
const [effectiveDate, setEffectiveDate] = useState(null);

const handleEffectiveDateChange = (date) => {
  if (date) {
    setEffectiveDate(date);
  } else {
    setEffectiveDate(null);
  }
}

<DatePicker
  label="Effective Date"
  value={effectiveDate}
  onAccept={handleEffectiveDateChange}
  showTodayButton
  autoOk
  fullWidth
  clearable
  />
```

**Comment by dmtrKovalenko** [comment] 2019-06-08 07:50
Duplicate of #1049

**Closed by dmtrKovalenko** 2019-06-08 07:50 UTC
