### ISSUE TITLE
DateRangePicker - add premade intervals (last week, last month, last year)

### ISSUE THREAD

**Issue by Cristy94** [mui-org/material-ui-pickers#1738] opened 2020-05-04 16:02 UTC
**Is your feature request related to a problem? Please describe.**
I am trying to add premade intervals to the picker, something like:
 * Today
 * This month
 * Last month
 * Last 30 days
 * Last year

**Describe the solution you'd like**
Currently I could add this by having a way to append data after the picker. I can generate the intervals myself, I just need a way to add extra UI to the picker.

**Describe alternatives you've considered**
I tried adding the premade intervals instead of the "clear" button, but then I have a list of buttons in another button.
Maybe the picker could have a list of ranges you can pass, in the form of `{range: {start, end}, label: string}` and it will automatically render those options so the user can quickly select those intervals.

**Additional context**
This is how it currently looks with a list passed as `clearLabel` prop:
![image](https://user-images.githubusercontent.com/1384885/80986846-6bb83f00-8e31-11ea-8774-802d315a8251.png)

**Comment by oliviertassinari** [comment] 2020-05-04 16:22
Duplicate of #1659

**Closed as completed by oliviertassinari** 2020-05-04 16:22 UTC
Labels: duplicate

**Comment by Cristy94** [comment] 2020-05-04 18:54
Until that is implemented, is there any way to append extra data to the DatePicker modal?
