### ISSUE TITLE
KeyboardDatePicker: datepicker is subtracting 1 day when entering dates manually in MM/dd/yyyy format

### ISSUE THREAD

**Issue by michaeljarizala** [mui-org/material-ui-pickers#1727] opened 2020-04-30 08:53 UTC
## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers | ^3.2.10 |
| material-ui          |core ^4.9.3 |
| React                | ^16.12.0|
| Browser              | chrome 81.0.4044.122 |
| Peer library         |date-fns ^2.10.0|moment ^2.22.2|

## Steps to reproduce
Use this configuration for the KeyboardDatePicker
```
<KeyboardDatePicker
  variant="inline"
  format="MM / dd / yyyy"
  emptyLabel="mm / dd / yyyy"
  margin="normal"
  label="Validity Date"
  value={state.myDate}
  onChange={handleChange_picker}
/>
```

## Expected behavior
When I manually enter a date `(MM / dd / yyyy)` in the textfield (without using the actual picker), it should save as it is in my database.  My frontend logic submits the date to server via ajax, and backend (Django) receives it without any extra processing or formatting. So what I entered, I should get.

## Actual behavior
But what actually happens is that for some reason, the `day` gets subtracted with `1` value. So when I enter `04/30/2020`, what I end up getting in the database is `04/29/2020`.

This only happens when I enter it manually. But when I pick from the picker, everything's good. What's strange is when I console.log the date value (during onChange event), the value is good. But when I submit the actual ajax request and check on request data, the day is then deducted with 1.

Screenshot: https://prnt.sc/s8hh1j

## Live example
This is the sample configuration that I have.
https://1gxzr.csb.app/

**Comment by dmtrKovalenko** [comment] 2020-05-01 10:26
It is not reproducing for me, so it looks like your local timezone issue. Make sure that your local `new Date()` is not returning previous date.

**Comment by oliviertassinari** [comment] 2020-05-05 08:59
Closing by lack of information, we can't reproduce.

**Closed as completed by oliviertassinari** 2020-05-05 08:59 UTC
Labels: status: incomplete

**Comment by michaeljarizala** [comment] 2020-05-06 13:01
Wait, when you pick from the picker, the value remains to be right. The problem only happens when you MANUALLY TYPE the date in the input field.

I've checked the actual value returned by each way for the date `04/10/2020`:
1. When I choose from the picker, it gives me `2020-04-10T00:00:00.000Z`.
2. When I manually type via the input field, I get `2020-04-09T16:00:00.000Z`

Note that the plugins raw value is directly passed into a state bare (not wrapping it in Date(), moment(), whatever), so what I set from the date field, I should get.

Also note `T00:00:00` vs `T16:00:00` so this for sure has something to do with timezone. But ain't this on the end of the plugin and not my server or local time configuration whatsoever? Or am I missing something in my KeyboardDatePicker like is the format prop correct?

**Comment by oliviertassinari** [comment] 2020-05-06 13:14
@michaeljarizala A duplicate of #1526 then?

**Comment by michaeljarizala** [comment] 2020-05-07 03:44
> @michaeljarizala A duplicate of #1526 then?

Oh there it is. But hmm I see it's still an open issue huh; but will keep track on this then.

Thanks for mentioning that here.

**Comment by eswarant** [comment] 2020-10-20 04:11
I am also facing this issue. Please let me know the solution for this issue

**Comment by eswarant** [comment] 2020-10-20 06:15
I just use this below way to fix this issue.
Selecting through date picker: Tue Oct 20 2020 10:56:00 GMT+0530 
Typing manually: Tue Oct 20 2020 00:00:00 GMT+0530 
So i just add time that is 10:56:00 when typing manually date then i dont see this issue

**Comment by evdokiamina** [comment] 2021-06-14 08:39
> I just use this below way to fix this issue.
> Selecting through date picker: Tue Oct 20 2020 10:56:00 GMT+0530
> Typing manually: Tue Oct 20 2020 00:00:00 GMT+0530
> So i just add time that is 10:56:00 when typing manually date then i dont see this issue

Changing the time to 10:56:00 worked for me!

**Comment by Pedroor** [comment] 2023-02-16 13:20
try 



`
import { parseISO } from 'date-fns'; 

<KeyboardDatePicker
  variant="inline"
  format="MM / dd / yyyy"
  emptyLabel="mm / dd / yyyy"
  margin="normal"
  label="Validity Date"
  value={parseISO(state.myDate)}
  onChange={handleChange_picker}
/>`
