### ISSUE TITLE
@material-ui/pickers Error in Dialog

### ISSUE THREAD

**Issue by oyb81076** [mui-org/material-ui-pickers#1333] opened 2019-09-29 15:26 UTC
```jsx
<Dialog>
   <MuiPickersUtilsProvider utils={DateFnsUtils}>
      <KeyboardDateTimePicker
            label="日期"
            disableToolbar
            variant="inline"
            value={selectedDate}
            onChange={handleChange}
          />
   </MuiPickersUtilsProvider>
</Dialog>
```
<img width="1244" alt="屏幕快照 2019-09-29 下午11 25 31" src="https://user-images.githubusercontent.com/6634415/65834720-71d0c500-e310-11e9-9360-394c5b1e7b7a.png">
```
"@material-ui/pickers": "^3.2.6",
"@date-io/date-fns": "^1.3.11",
"date-fns": "^2.4.1",
```

**Comment by oyb81076** [comment] 2019-10-01 06:26
seem just happens when umd import other library
```
<script src="/node_modules/react/umd/react.development.js"></script>
<script src="/node_modules/react-dom/umd/react-dom.development.js"></script>
<script src="/node_modules/prop-types/prop-types.min.js"></script>
<script src="/node_modules/@material-ui/core/umd/material-ui.development.js"></script>
```
and find an other problem,  ``<script src="/node_modules/@material-ui/pickers/dist/material-ui-pickers.umd.js"></script>`` does not work.  global["material-ui"] is not defined
```js
// <script src="/node_modules/@material-ui/pickers/dist/material-ui-pickers.umd.js"></script>
(function (global, factory) {
  typeof exports === 'object' && typeof module !== 'undefined' ? factory(exports, require('react'), require('@material-ui/core/Typography'), require('@material-ui/core/styles'), require('@material-ui/core/Button'), require('@material-ui/core/Toolbar'), require('@material-ui/core/TextField'), require('@material-ui/core/IconButton'), require('@material-ui/core/InputAdornment'), require('@material-ui/core/SvgIcon'), require('react-dom'), require('@material-ui/core/CircularProgress'), require('@material-ui/core/DialogActions'), require('@material-ui/core/DialogContent'), require('@material-ui/core/Dialog'), require('@material-ui/core/Popover'), require('@material-ui/core/Grid'), require('@material-ui/core/Tab'), require('@material-ui/core/Tabs'), require('@material-ui/core/Paper')) :
  typeof define === 'function' && define.amd ? define(['exports', 'react', '@material-ui/core/Typography', '@material-ui/core/styles', '@material-ui/core/Button', '@material-ui/core/Toolbar', '@material-ui/core/TextField', '@material-ui/core/IconButton', '@material-ui/core/InputAdornment', '@material-ui/core/SvgIcon', 'react-dom', '@material-ui/core/CircularProgress', '@material-ui/core/DialogActions', '@material-ui/core/DialogContent', '@material-ui/core/Dialog', '@material-ui/core/Popover', '@material-ui/core/Grid', '@material-ui/core/Tab', '@material-ui/core/Tabs', '@material-ui/core/Paper'], factory) :
  (global = global || self, factory(global['@material-ui/pickers'] = {}, global.React, global['material-ui'].Typography, global['material-ui'], global['material-ui'].Button, global['material-ui'].Toolbar, global['material-ui'].TextField, global['material-ui'].IconButton, global['material-ui'].InputAdornment, global['material-ui'].SvgIcon, global.ReactDOM, global['material-ui'].CircularProgress, global['material-ui'].DialogActions, global['material-ui'].DialogContent, global['material-ui'].Dialog, global['material-ui'].Popover, global['material-ui'].Grid, global['material-ui'].Tab, global['material-ui'].Tabs, global['material-ui'].Paper));
}(this, function (exports, React, Typography, styles$5, Button, Toolbar, TextField, IconButton, InputAdornment, SvgIcon, ReactDOM, CircularProgress, DialogActions, DialogContent, Dialog, Popover, Grid, Tab, Tabs, Paper) { 'use strict';
```

**Comment by voidpp** [comment] 2019-10-19 10:03
I have a similar problem. The umd build of the current version @material-ui/pickers use the 3.x version of the @material-ui/core (`global["material-ui"]`). 
The 4.x material-ui defines itself in the MaterialUI global variable. (`global.MaterialUI`)

**Comment by lyvyu** [comment] 2019-12-02 13:08
Hey, did anyone had the chance to make this working with UMD and latest version of React Material ?!

**Comment by dmtrKovalenko** [comment] 2020-02-23 12:35
Duplicate of other issue

**Closed as completed by dmtrKovalenko** 2020-02-23 12:35 UTC
