### ISSUE TITLE
Spreading DateRangeDayProps into PickersDay cause warnings

### ISSUE THREAD

**Issue by aamirafridi** [mui-org/material-ui-pickers#2052] opened 2020-07-30 18:31 UTC
version `v4-0-0-alpha-10`

#### Demo
https://codesandbox.io/s/material-ui-date-range-xz2w2?file=/src/index.tsx
check console

```javascript

const renderCustomDay = (
  date: unknown,
  dateRangeDayProps: DateRangeDayProps
) => {
  const {
    isPreviewing,
    isStartOfPreviewing,
    isEndOfPreviewing,
    isHighlighting,
    isStartOfHighlighting,
    isEndOfHighlighting,
    ...rest
  } = dateRangeDayProps;

  return (
    <PickersDay
      {...rest} // if I spread {...dateRangeDayProps} here I get following warnings
      disableMargin
    />
  );
};

<DateRangePicker
  {...props}
  disablePast
  renderDay={renderCustomDay}
/>
```

### Warnings in console

```
react-dom.development.js:88 Warning: React does not recognize the `isPreviewing` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `ispreviewing` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in button (created by ForwardRef(ButtonBase))
    in ForwardRef(ButtonBase) (created by WithStyles(ForwardRef(ButtonBase)))
    in WithStyles(ForwardRef(ButtonBase)) (created by PickersDay)
    in PickersDay
    in PickersDay (created by WithDefaultProps(PickersDay))
    in WithDefaultProps(PickersDay) (at HolidayDatePicker.restricted.tsx:91)
    in div (created by PickersCalendar)
    in div (created by PickersCalendar)
    in Transition (created by CSSTransition)
    in CSSTransition (created by SlideTransition)
    in div (created by TransitionGroup)
    in TransitionGroup (created by SlideTransition)
    in SlideTransition (created by PickersCalendar)
    in PickersCalendar (created by Calendar)
    in Calendar (created by DateRangePickerViewDesktop)
    in div (created by DateRangePickerViewDesktop)
    in div (created by DateRangePickerViewDesktop)
    in DateRangePickerViewDesktop (created by DateRangePickerView)
    in div (created by DateRangePickerView)
    in DateRangePickerView (created by RangePickerWithStateAndWrapper)
    in div (created by ForwardRef(Paper))
    in ForwardRef(Paper) (created by WithStyles(ForwardRef(Paper)))
    in WithStyles(ForwardRef(Paper)) (created by Transition)
    in Transition (created by ForwardRef(Grow))
    in ForwardRef(Grow) (created by Unstable_TrapFocus)
    in Unstable_TrapFocus (created by ForwardRef(Popper))
    in div (created by ForwardRef(Popper))
    in ForwardRef(Portal) (created by ForwardRef(Popper))
    in ForwardRef(Popper) (created by PickersPopper)
    in PickersPopper (created by DesktopTooltipWrapper)
    in DesktopTooltipWrapper (created by WrapperComponent)
    in WrapperComponent (created by RangePickerWithStateAndWrapper)
    in RangePickerWithStateAndWrapper (created by DesktopDateRangePicker)
    in DesktopDateRangePicker (created by WithDefaultProps(DesktopDateRangePicker))
    in WithDefaultProps(DesktopDateRangePicker) (created by ForwardRef)
    in ForwardRef (at DateRangePicker.tsx:111)
    in PickersLocalizationProvider (created by WithDefaultProps(PickersLocalizationProvider))
    in WithDefaultProps(PickersLocalizationProvider) (at DateRangePicker.tsx:109)
    in DateRangePicker (at HolidayDatePicker.restricted.tsx:123)
    in ThemeProvider (at Theme/index.tsx:130)
    in StylesProvider (at Theme/index.tsx:127)
    in ThemeProvider (at HolidayDatePicker.restricted.tsx:122)
    in div (created by ForwardRef(FormControl))
    in ForwardRef(FormControl) (created by WithStyles(ForwardRef(FormControl)))
    in WithStyles(ForwardRef(FormControl)) (at HolidayDatePicker.restricted.tsx:121)
    in HolidayDatePickerRestricted (at HolidayDatePicker.tsx:36)
    in HolidayDatePicker (at HolidayDatePicker.stories.tsx:64)
    in ThemeProvider (at Theme/index.tsx:130)
    in StylesProvider (at Theme/index.tsx:127)
    in ThemeProvider (at HolidayDatePicker.stories.tsx:49)
    in div (at preview.js:5)
    in storyFn
    in ErrorBoundary
printWarning @ react-dom.development.js:88
error @ react-dom.development.js:60
validateProperty$1 @ react-dom.development.js:5549
warnUnknownProperties @ react-dom.development.js:5595
validateProperties$2 @ react-dom.development.js:5619
validatePropertiesInDevelopment @ react-dom.development.js:5662
setInitialProperties @ react-dom.development.js:5941
finalizeInitialChildren @ react-dom.development.js:7499
completeWork @ react-dom.development.js:18978
completeUnitOfWork @ react-dom.development.js:22192
performUnitOfWork @ react-dom.development.js:22165
workLoopSync @ react-dom.development.js:22130
performSyncWorkOnRoot @ react-dom.development.js:21756
(anonymous) @ react-dom.development.js:11089
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushSyncCallbackQueueImpl @ react-dom.development.js:11084
flushSyncCallbackQueue @ react-dom.development.js:11072
flushPassiveEffectsImpl @ react-dom.development.js:22883
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushPassiveEffects @ react-dom.development.js:22820
(anonymous) @ react-dom.development.js:22699
workLoop @ scheduler.development.js:597
flushWork @ scheduler.development.js:552
performWorkUntilDeadline @ scheduler.development.js:164
react-dom.development.js:88 Warning: React does not recognize the `isStartOfPreviewing` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `isstartofpreviewing` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in button (created by ForwardRef(ButtonBase))
    in ForwardRef(ButtonBase) (created by WithStyles(ForwardRef(ButtonBase)))
    in WithStyles(ForwardRef(ButtonBase)) (created by PickersDay)
    in PickersDay
    in PickersDay (created by WithDefaultProps(PickersDay))
    in WithDefaultProps(PickersDay) (at HolidayDatePicker.restricted.tsx:91)
    in div (created by PickersCalendar)
    in div (created by PickersCalendar)
    in Transition (created by CSSTransition)
    in CSSTransition (created by SlideTransition)
    in div (created by TransitionGroup)
    in TransitionGroup (created by SlideTransition)
    in SlideTransition (created by PickersCalendar)
    in PickersCalendar (created by Calendar)
    in Calendar (created by DateRangePickerViewDesktop)
    in div (created by DateRangePickerViewDesktop)
    in div (created by DateRangePickerViewDesktop)
    in DateRangePickerViewDesktop (created by DateRangePickerView)
    in div (created by DateRangePickerView)
    in DateRangePickerView (created by RangePickerWithStateAndWrapper)
    in div (created by ForwardRef(Paper))
    in ForwardRef(Paper) (created by WithStyles(ForwardRef(Paper)))
    in WithStyles(ForwardRef(Paper)) (created by Transition)
    in Transition (created by ForwardRef(Grow))
    in ForwardRef(Grow) (created by Unstable_TrapFocus)
    in Unstable_TrapFocus (created by ForwardRef(Popper))
    in div (created by ForwardRef(Popper))
    in ForwardRef(Portal) (created by ForwardRef(Popper))
    in ForwardRef(Popper) (created by PickersPopper)
    in PickersPopper (created by DesktopTooltipWrapper)
    in DesktopTooltipWrapper (created by WrapperComponent)
    in WrapperComponent (created by RangePickerWithStateAndWrapper)
    in RangePickerWithStateAndWrapper (created by DesktopDateRangePicker)
    in DesktopDateRangePicker (created by WithDefaultProps(DesktopDateRangePicker))
    in WithDefaultProps(DesktopDateRangePicker) (created by ForwardRef)
    in ForwardRef (at DateRangePicker.tsx:111)
    in PickersLocalizationProvider (created by WithDefaultProps(PickersLocalizationProvider))
    in WithDefaultProps(PickersLocalizationProvider) (at DateRangePicker.tsx:109)
    in DateRangePicker (at HolidayDatePicker.restricted.tsx:123)
    in ThemeProvider (at Theme/index.tsx:130)
    in StylesProvider (at Theme/index.tsx:127)
    in ThemeProvider (at HolidayDatePicker.restricted.tsx:122)
    in div (created by ForwardRef(FormControl))
    in ForwardRef(FormControl) (created by WithStyles(ForwardRef(FormControl)))
    in WithStyles(ForwardRef(FormControl)) (at HolidayDatePicker.restricted.tsx:121)
    in HolidayDatePickerRestricted (at HolidayDatePicker.tsx:36)
    in HolidayDatePicker (at HolidayDatePicker.stories.tsx:64)
    in ThemeProvider (at Theme/index.tsx:130)
    in StylesProvider (at Theme/index.tsx:127)
    in ThemeProvider (at HolidayDatePicker.stories.tsx:49)
    in div (at preview.js:5)
    in storyFn
    in ErrorBoundary
printWarning @ react-dom.development.js:88
error @ react-dom.development.js:60
validateProperty$1 @ react-dom.development.js:5549
warnUnknownProperties @ react-dom.development.js:5595
validateProperties$2 @ react-dom.development.js:5619
validatePropertiesInDevelopment @ react-dom.development.js:5662
setInitialProperties @ react-dom.development.js:5941
finalizeInitialChildren @ react-dom.development.js:7499
completeWork @ react-dom.development.js:18978
completeUnitOfWork @ react-dom.development.js:22192
performUnitOfWork @ react-dom.development.js:22165
workLoopSync @ react-dom.development.js:22130
performSyncWorkOnRoot @ react-dom.development.js:21756
(anonymous) @ react-dom.development.js:11089
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushSyncCallbackQueueImpl @ react-dom.development.js:11084
flushSyncCallbackQueue @ react-dom.development.js:11072
flushPassiveEffectsImpl @ react-dom.development.js:22883
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushPassiveEffects @ react-dom.development.js:22820
(anonymous) @ react-dom.development.js:22699
workLoop @ scheduler.development.js:597
flushWork @ scheduler.development.js:552
performWorkUntilDeadline @ scheduler.development.js:164
react-dom.development.js:88 Warning: React does not recognize the `isEndOfPreviewing` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `isendofpreviewing` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in button (created by ForwardRef(ButtonBase))
    in ForwardRef(ButtonBase) (created by WithStyles(ForwardRef(ButtonBase)))
    in WithStyles(ForwardRef(ButtonBase)) (created by PickersDay)
    in PickersDay
    in PickersDay (created by WithDefaultProps(PickersDay))
    in WithDefaultProps(PickersDay) (at HolidayDatePicker.restricted.tsx:91)
    in div (created by PickersCalendar)
    in div (created by PickersCalendar)
    in Transition (created by CSSTransition)
    in CSSTransition (created by SlideTransition)
    in div (created by TransitionGroup)
    in TransitionGroup (created by SlideTransition)
    in SlideTransition (created by PickersCalendar)
    in PickersCalendar (created by Calendar)
    in Calendar (created by DateRangePickerViewDesktop)
    in div (created by DateRangePickerViewDesktop)
    in div (created by DateRangePickerViewDesktop)
    in DateRangePickerViewDesktop (created by DateRangePickerView)
    in div (created by DateRangePickerView)
    in DateRangePickerView (created by RangePickerWithStateAndWrapper)
    in div (created by ForwardRef(Paper))
    in ForwardRef(Paper) (created by WithStyles(ForwardRef(Paper)))
    in WithStyles(ForwardRef(Paper)) (created by Transition)
    in Transition (created by ForwardRef(Grow))
    in ForwardRef(Grow) (created by Unstable_TrapFocus)
    in Unstable_TrapFocus (created by ForwardRef(Popper))
    in div (created by ForwardRef(Popper))
    in ForwardRef(Portal) (created by ForwardRef(Popper))
    in ForwardRef(Popper) (created by PickersPopper)
    in PickersPopper (created by DesktopTooltipWrapper)
    in DesktopTooltipWrapper (created by WrapperComponent)
    in WrapperComponent (created by RangePickerWithStateAndWrapper)
    in RangePickerWithStateAndWrapper (created by DesktopDateRangePicker)
    in DesktopDateRangePicker (created by WithDefaultProps(DesktopDateRangePicker))
    in WithDefaultProps(DesktopDateRangePicker) (created by ForwardRef)
    in ForwardRef (at DateRangePicker.tsx:111)
    in PickersLocalizationProvider (created by WithDefaultProps(PickersLocalizationProvider))
    in WithDefaultProps(PickersLocalizationProvider) (at DateRangePicker.tsx:109)
    in DateRangePicker (at HolidayDatePicker.restricted.tsx:123)
    in ThemeProvider (at Theme/index.tsx:130)
    in StylesProvider (at Theme/index.tsx:127)
    in ThemeProvider (at HolidayDatePicker.restricted.tsx:122)
    in div (created by ForwardRef(FormControl))
    in ForwardRef(FormControl) (created by WithStyles(ForwardRef(FormControl)))
    in WithStyles(ForwardRef(FormControl)) (at HolidayDatePicker.restricted.tsx:121)
    in HolidayDatePickerRestricted (at HolidayDatePicker.tsx:36)
    in HolidayDatePicker (at HolidayDatePicker.stories.tsx:64)
    in ThemeProvider (at Theme/index.tsx:130)
    in StylesProvider (at Theme/index.tsx:127)
    in ThemeProvider (at HolidayDatePicker.stories.tsx:49)
    in div (at preview.js:5)
    in storyFn
    in ErrorBoundary
printWarning @ react-dom.development.js:88
error @ react-dom.development.js:60
validateProperty$1 @ react-dom.development.js:5549
warnUnknownProperties @ react-dom.development.js:5595
validateProperties$2 @ react-dom.development.js:5619
validatePropertiesInDevelopment @ react-dom.development.js:5662
setInitialProperties @ react-dom.development.js:5941
finalizeInitialChildren @ react-dom.development.js:7499
completeWork @ react-dom.development.js:18978
completeUnitOfWork @ react-dom.development.js:22192
performUnitOfWork @ react-dom.development.js:22165
workLoopSync @ react-dom.development.js:22130
performSyncWorkOnRoot @ react-dom.development.js:21756
(anonymous) @ react-dom.development.js:11089
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushSyncCallbackQueueImpl @ react-dom.development.js:11084
flushSyncCallbackQueue @ react-dom.development.js:11072
flushPassiveEffectsImpl @ react-dom.development.js:22883
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushPassiveEffects @ react-dom.development.js:22820
(anonymous) @ react-dom.development.js:22699
workLoop @ scheduler.development.js:597
flushWork @ scheduler.development.js:552
performWorkUntilDeadline @ scheduler.development.js:164
react-dom.development.js:88 Warning: React does not recognize the `isHighlighting` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `ishighlighting` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in button (created by ForwardRef(ButtonBase))
    in ForwardRef(ButtonBase) (created by WithStyles(ForwardRef(ButtonBase)))
    in WithStyles(ForwardRef(ButtonBase)) (created by PickersDay)
    in PickersDay
    in PickersDay (created by WithDefaultProps(PickersDay))
    in WithDefaultProps(PickersDay) (at HolidayDatePicker.restricted.tsx:91)
    in div (created by PickersCalendar)
    in div (created by PickersCalendar)
    in Transition (created by CSSTransition)
    in CSSTransition (created by SlideTransition)
    in div (created by TransitionGroup)
    in TransitionGroup (created by SlideTransition)
    in SlideTransition (created by PickersCalendar)
    in PickersCalendar (created by Calendar)
    in Calendar (created by DateRangePickerViewDesktop)
    in div (created by DateRangePickerViewDesktop)
    in div (created by DateRangePickerViewDesktop)
    in DateRangePickerViewDesktop (created by DateRangePickerView)
    in div (created by DateRangePickerView)
    in DateRangePickerView (created by RangePickerWithStateAndWrapper)
    in div (created by ForwardRef(Paper))
    in ForwardRef(Paper) (created by WithStyles(ForwardRef(Paper)))
    in WithStyles(ForwardRef(Paper)) (created by Transition)
    in Transition (created by ForwardRef(Grow))
    in ForwardRef(Grow) (created by Unstable_TrapFocus)
    in Unstable_TrapFocus (created by ForwardRef(Popper))
    in div (created by ForwardRef(Popper))
    in ForwardRef(Portal) (created by ForwardRef(Popper))
    in ForwardRef(Popper) (created by PickersPopper)
    in PickersPopper (created by DesktopTooltipWrapper)
    in DesktopTooltipWrapper (created by WrapperComponent)
    in WrapperComponent (created by RangePickerWithStateAndWrapper)
    in RangePickerWithStateAndWrapper (created by DesktopDateRangePicker)
    in DesktopDateRangePicker (created by WithDefaultProps(DesktopDateRangePicker))
    in WithDefaultProps(DesktopDateRangePicker) (created by ForwardRef)
    in ForwardRef (at DateRangePicker.tsx:111)
    in PickersLocalizationProvider (created by WithDefaultProps(PickersLocalizationProvider))
    in WithDefaultProps(PickersLocalizationProvider) (at DateRangePicker.tsx:109)
    in DateRangePicker (at HolidayDatePicker.restricted.tsx:123)
    in ThemeProvider (at Theme/index.tsx:130)
    in StylesProvider (at Theme/index.tsx:127)
    in ThemeProvider (at HolidayDatePicker.restricted.tsx:122)
    in div (created by ForwardRef(FormControl))
    in ForwardRef(FormControl) (created by WithStyles(ForwardRef(FormControl)))
    in WithStyles(ForwardRef(FormControl)) (at HolidayDatePicker.restricted.tsx:121)
    in HolidayDatePickerRestricted (at HolidayDatePicker.tsx:36)
    in HolidayDatePicker (at HolidayDatePicker.stories.tsx:64)
    in ThemeProvider (at Theme/index.tsx:130)
    in StylesProvider (at Theme/index.tsx:127)
    in ThemeProvider (at HolidayDatePicker.stories.tsx:49)
    in div (at preview.js:5)
    in storyFn
    in ErrorBoundary
printWarning @ react-dom.development.js:88
error @ react-dom.development.js:60
validateProperty$1 @ react-dom.development.js:5549
warnUnknownProperties @ react-dom.development.js:5595
validateProperties$2 @ react-dom.development.js:5619
validatePropertiesInDevelopment @ react-dom.development.js:5662
setInitialProperties @ react-dom.development.js:5941
finalizeInitialChildren @ react-dom.development.js:7499
completeWork @ react-dom.development.js:18978
completeUnitOfWork @ react-dom.development.js:22192
performUnitOfWork @ react-dom.development.js:22165
workLoopSync @ react-dom.development.js:22130
performSyncWorkOnRoot @ react-dom.development.js:21756
(anonymous) @ react-dom.development.js:11089
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushSyncCallbackQueueImpl @ react-dom.development.js:11084
flushSyncCallbackQueue @ react-dom.development.js:11072
flushPassiveEffectsImpl @ react-dom.development.js:22883
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushPassiveEffects @ react-dom.development.js:22820
(anonymous) @ react-dom.development.js:22699
workLoop @ scheduler.development.js:597
flushWork @ scheduler.development.js:552
performWorkUntilDeadline @ scheduler.development.js:164
react-dom.development.js:88 Warning: React does not recognize the `isStartOfHighlighting` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `isstartofhighlighting` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in button (created by ForwardRef(ButtonBase))
    in ForwardRef(ButtonBase) (created by WithStyles(ForwardRef(ButtonBase)))
    in WithStyles(ForwardRef(ButtonBase)) (created by PickersDay)
    in PickersDay
    in PickersDay (created by WithDefaultProps(PickersDay))
    in WithDefaultProps(PickersDay) (at HolidayDatePicker.restricted.tsx:91)
    in div (created by PickersCalendar)
    in div (created by PickersCalendar)
    in Transition (created by CSSTransition)
    in CSSTransition (created by SlideTransition)
    in div (created by TransitionGroup)
    in TransitionGroup (created by SlideTransition)
    in SlideTransition (created by PickersCalendar)
    in PickersCalendar (created by Calendar)
    in Calendar (created by DateRangePickerViewDesktop)
    in div (created by DateRangePickerViewDesktop)
    in div (created by DateRangePickerViewDesktop)
    in DateRangePickerViewDesktop (created by DateRangePickerView)
    in div (created by DateRangePickerView)
    in DateRangePickerView (created by RangePickerWithStateAndWrapper)
    in div (created by ForwardRef(Paper))
    in ForwardRef(Paper) (created by WithStyles(ForwardRef(Paper)))
    in WithStyles(ForwardRef(Paper)) (created by Transition)
    in Transition (created by ForwardRef(Grow))
    in ForwardRef(Grow) (created by Unstable_TrapFocus)
    in Unstable_TrapFocus (created by ForwardRef(Popper))
    in div (created by ForwardRef(Popper))
    in ForwardRef(Portal) (created by ForwardRef(Popper))
    in ForwardRef(Popper) (created by PickersPopper)
    in PickersPopper (created by DesktopTooltipWrapper)
    in DesktopTooltipWrapper (created by WrapperComponent)
    in WrapperComponent (created by RangePickerWithStateAndWrapper)
    in RangePickerWithStateAndWrapper (created by DesktopDateRangePicker)
    in DesktopDateRangePicker (created by WithDefaultProps(DesktopDateRangePicker))
    in WithDefaultProps(DesktopDateRangePicker) (created by ForwardRef)
    in ForwardRef (at DateRangePicker.tsx:111)
    in PickersLocalizationProvider (created by WithDefaultProps(PickersLocalizationProvider))
    in WithDefaultProps(PickersLocalizationProvider) (at DateRangePicker.tsx:109)
    in DateRangePicker (at HolidayDatePicker.restricted.tsx:123)
    in ThemeProvider (at Theme/index.tsx:130)
    in StylesProvider (at Theme/index.tsx:127)
    in ThemeProvider (at HolidayDatePicker.restricted.tsx:122)
    in div (created by ForwardRef(FormControl))
    in ForwardRef(FormControl) (created by WithStyles(ForwardRef(FormControl)))
    in WithStyles(ForwardRef(FormControl)) (at HolidayDatePicker.restricted.tsx:121)
    in HolidayDatePickerRestricted (at HolidayDatePicker.tsx:36)
    in HolidayDatePicker (at HolidayDatePicker.stories.tsx:64)
    in ThemeProvider (at Theme/index.tsx:130)
    in StylesProvider (at Theme/index.tsx:127)
    in ThemeProvider (at HolidayDatePicker.stories.tsx:49)
    in div (at preview.js:5)
    in storyFn
    in ErrorBoundary
printWarning @ react-dom.development.js:88
error @ react-dom.development.js:60
validateProperty$1 @ react-dom.development.js:5549
warnUnknownProperties @ react-dom.development.js:5595
validateProperties$2 @ react-dom.development.js:5619
validatePropertiesInDevelopment @ react-dom.development.js:5662
setInitialProperties @ react-dom.development.js:5941
finalizeInitialChildren @ react-dom.development.js:7499
completeWork @ react-dom.development.js:18978
completeUnitOfWork @ react-dom.development.js:22192
performUnitOfWork @ react-dom.development.js:22165
workLoopSync @ react-dom.development.js:22130
performSyncWorkOnRoot @ react-dom.development.js:21756
(anonymous) @ react-dom.development.js:11089
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushSyncCallbackQueueImpl @ react-dom.development.js:11084
flushSyncCallbackQueue @ react-dom.development.js:11072
flushPassiveEffectsImpl @ react-dom.development.js:22883
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushPassiveEffects @ react-dom.development.js:22820
(anonymous) @ react-dom.development.js:22699
workLoop @ scheduler.development.js:597
flushWork @ scheduler.development.js:552
performWorkUntilDeadline @ scheduler.development.js:164
react-dom.development.js:88 Warning: React does not recognize the `isEndOfHighlighting` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `isendofhighlighting` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in button (created by ForwardRef(ButtonBase))
    in ForwardRef(ButtonBase) (created by WithStyles(ForwardRef(ButtonBase)))
    in WithStyles(ForwardRef(ButtonBase)) (created by PickersDay)
    in PickersDay
    in PickersDay (created by WithDefaultProps(PickersDay))
    in WithDefaultProps(PickersDay) (at HolidayDatePicker.restricted.tsx:91)
    in div (created by PickersCalendar)
    in div (created by PickersCalendar)
    in Transition (created by CSSTransition)
    in CSSTransition (created by SlideTransition)
    in div (created by TransitionGroup)
    in TransitionGroup (created by SlideTransition)
    in SlideTransition (created by PickersCalendar)
    in PickersCalendar (created by Calendar)
    in Calendar (created by DateRangePickerViewDesktop)
    in div (created by DateRangePickerViewDesktop)
    in div (created by DateRangePickerViewDesktop)
    in DateRangePickerViewDesktop (created by DateRangePickerView)
    in div (created by DateRangePickerView)
    in DateRangePickerView (created by RangePickerWithStateAndWrapper)
    in div (created by ForwardRef(Paper))
    in ForwardRef(Paper) (created by WithStyles(ForwardRef(Paper)))
    in WithStyles(ForwardRef(Paper)) (created by Transition)
    in Transition (created by ForwardRef(Grow))
    in ForwardRef(Grow) (created by Unstable_TrapFocus)
    in Unstable_TrapFocus (created by ForwardRef(Popper))
    in div (created by ForwardRef(Popper))
    in ForwardRef(Portal) (created by ForwardRef(Popper))
    in ForwardRef(Popper) (created by PickersPopper)
    in PickersPopper (created by DesktopTooltipWrapper)
    in DesktopTooltipWrapper (created by WrapperComponent)
    in WrapperComponent (created by RangePickerWithStateAndWrapper)
    in RangePickerWithStateAndWrapper (created by DesktopDateRangePicker)
    in DesktopDateRangePicker (created by WithDefaultProps(DesktopDateRangePicker))
    in WithDefaultProps(DesktopDateRangePicker) (created by ForwardRef)
    in ForwardRef (at DateRangePicker.tsx:111)
    in PickersLocalizationProvider (created by WithDefaultProps(PickersLocalizationProvider))
    in WithDefaultProps(PickersLocalizationProvider) (at DateRangePicker.tsx:109)
    in DateRangePicker (at HolidayDatePicker.restricted.tsx:123)
    in ThemeProvider (at Theme/index.tsx:130)
    in StylesProvider (at Theme/index.tsx:127)
    in ThemeProvider (at HolidayDatePicker.restricted.tsx:122)
    in div (created by ForwardRef(FormControl))
    in ForwardRef(FormControl) (created by WithStyles(ForwardRef(FormControl)))
    in WithStyles(ForwardRef(FormControl)) (at HolidayDatePicker.restricted.tsx:121)
    in HolidayDatePickerRestricted (at HolidayDatePicker.tsx:36)
    in HolidayDatePicker (at HolidayDatePicker.stories.tsx:64)
    in ThemeProvider (at Theme/index.tsx:130)
    in StylesProvider (at Theme/index.tsx:127)
    in ThemeProvider (at HolidayDatePicker.stories.tsx:49)
    in div (at preview.js:5)
    in storyFn
    in ErrorBoundary
printWarning @ react-dom.development.js:88
error @ react-dom.development.js:60
validateProperty$1 @ react-dom.development.js:5549
warnUnknownProperties @ react-dom.development.js:5595
validateProperties$2 @ react-dom.development.js:5619
validatePropertiesInDevelopment @ react-dom.development.js:5662
setInitialProperties @ react-dom.development.js:5941
finalizeInitialChildren @ react-dom.development.js:7499
completeWork @ react-dom.development.js:18978
completeUnitOfWork @ react-dom.development.js:22192
performUnitOfWork @ react-dom.development.js:22165
workLoopSync @ react-dom.development.js:22130
performSyncWorkOnRoot @ react-dom.development.js:21756
(anonymous) @ react-dom.development.js:11089
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushSyncCallbackQueueImpl @ react-dom.development.js:11084
flushSyncCallbackQueue @ react-dom.development.js:11072
flushPassiveEffectsImpl @ react-dom.development.js:22883
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushPassiveEffects @ react-dom.development.js:22820
(anonymous) @ react-dom.development.js:22699
workLoop @ scheduler.development.js:597
flushWork @ scheduler.development.js:552
performWorkUntilDeadline @ scheduler.development.js:164
```

**Comment by oliviertassinari** [comment] 2020-07-30 18:34
Duplicate of #1997

**Closed as completed** 2020-07-30 18:35 UTC
Labels: duplicate
