### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded. (>= v4.0.0-alpha.8)

### ISSUE THREAD

**Issue by BowlingX** [mui-org/material-ui-pickers#1974] opened 2020-07-11 15:32 UTC
Since version `alpha.8` I get this error message when I use the pickers inside a Modal. It seems to be a similar issue that was already present here: #471

```
Uncaught RangeError: Maximum call stack size exceeded at HTMLDocument.contain (Unstable_TrapFocus.js?311c:77)
```
I created a new bug report as the old one was closed and not related to the newer version.
I created a sandbox here: https://codesandbox.io/s/bold-kare-0mcpc
The Issue appears when the picker dialog opens. It's also not possible to close it.

If I add the `disableEnforceFocus` prop to the dialog the error message changes to `Uncaught Error: Cannot add node 1 because a node with that id is already in the Store.`.

- [x] The issue is present in the latest release.

| Tech        | Version |
| ----------- | ------- |
| @material-ui/core | v4.11.0 |
| @material-ui/pickers | >= v4.0.0-alpha.8  |
| React       |      16.13.1   |
| Browser     |    Chrome     |

**Comment by BowlingX** [comment] 2020-07-11 15:58
Ok the `Uncaught Error: Cannot add node 1 because a node with that id is already in the Store..` error I can't reproduce anymore. The only issue seems to be then that the picker das not close when I click on the background.

**Comment by dmtrKovalenko** [comment] 2020-07-11 16:00
Duplicate of #1852

**Closed as completed** 2020-07-11 16:00 UTC
Labels: duplicate
