### ISSUE TITLE
Implement React.forwardRef

### ISSUE THREAD

**Issue by mschipperheyn** [mui-org/material-ui-pickers#1434] opened 2019-12-27 11:48 UTC
<details>
  <summary>Support request</summary>

Refs don't seem to be passed on to the underlying input field.

## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |      3.2.8   |
| material-ui          |      4.7.2   |
| TypeScript           |         |
| React                |    16.12     |
| Browser              |         |
| Peer library         |   luxon  1.21.2    |

## Steps to reproduce

```
const DatePickerFieldEl = ({
	input,
	label,
	placeholder,
	required,
	disabled,
	readOnly,
	meta: { touched, error, submitError, submitFailed },
	dateFormat,
	onChange,
	id,
	i18n,
	i18nHash,
	...rest
}) => {
	const inputRef = React.useRef(null);
	const { name, onChange: onChangeField, value, ...restInput } = input;
	const handleChange = React.useCallback(date => {
		if (onChangeField) onChangeField(date ? date.toJSDate() : null);
		if (onChange) onChange(date ? date.toJSDate() : null);

        // inputRef.current is always null
		inputRef.current.blur();

	}, []);
	return (
		<MuiPickersUtilsProvider utils={LuxonUtils}>
			<DatePickerMat
				{...rest}

				ref={inputRef}

				keyboard
				id={id}
				name={`${name}${required ? ` *` : ''}`}
				label={label}
				cancelLabel={i18n._(t('ui.cancel')`Cancelar`)}
				todayLabel={i18n._(t('ui.today')`Hoje`)}
				clearLabel={i18n._(t('ui.clear')`Limpar`)}
				okLabel={i18n._(t('ui.ok')`OK`)}
				invalidDateMessage={i18n._(t('ui.date.invalid')`Data invalido`)}
				value={value}
				onChange={handleChange}
				onAccept={handleChange}
				format={dateFormat || DATEFORMAT}
				placeholder={placeholder}
				keyboardIcon={<CalendarIcon color="primary" />}
				leftArrowIcon={<ArrowLeftIcon />}
				rightArrowIcon={<ArrowRightIcon />}
				inputProps={{
					...restInput,
					autocomplete: 'off',
				}}
			/>
		</MuiPickersUtilsProvider>
	);
};
```
## Expected behavior

The ref points to the input field.

## Actual behavior

ref is not passed on, remains null.

</details>

**Comment by oliviertassinari** [comment] 2020-01-04 13:55
@mschipperheyn We would appreciate if you could work on your issue templates. A live reproduction would have been significantly better. But I believe it's a support question. You can find the information in the documentation or ask on Stackoverflow.

---

However, in this case, it seems to uncover a broader issue. Most of the public components are missing the usage of `React.forwardRef` API as the components in the main repository have, e.g.
https://github.com/mui-org/material-ui-pickers/blob/689d7d33bdac5e649d4e5c6ca37f9f523c80b8cf/lib/src/Picker/makePickerWithState.tsx#L30-L36

**My proposal would be to forward the ref to the root element.**

**Comment by dmtrKovalenko** [comment] 2020-01-04 13:56
@oliviertassinari I dont think we can forward ref to the textfield. As we are using rifm

**Comment by oliviertassinari** [comment] 2020-01-04 14:04
The idea is to forward the ref to the root, not the input.

@mschipperheyn Regarding your issue, I believe it's a support question. You can find the information in the documentation or ask on Stackoverflow.

**Comment by mschipperheyn** [comment] 2020-01-09 18:01
You're right @oliviertassinari . Apologies.

**Comment by oliviertassinari** [comment] 2020-03-19 10:19
Duplicate of #1303

**Closed as completed by oliviertassinari** 2020-03-19 10:19 UTC
Labels: duplicate
