### ISSUE TITLE
onChange handler not called when only picking hours

### ISSUE THREAD

**Issue by hundekoerper** [mui-org/material-ui-pickers#1879] opened 2020-06-10 12:46 UTC
First of all thank you for your work on this library! It's realy neat :)

![A GIF or MEME to give some spice of the internet](https://media.giphy.com/media/vYtIhwaPVejPq/giphy.gif)

## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers | ^4.0.0-alpha.7        |

## Steps to reproduce
On desktop

1. Open a DateTimePicker (I'm using DesktopDateTimePicker) with the `autoOk` property
2. Pick an hour  
3. Close the picker instead of picking a minute
4. Open the time picker again to see that the internal state has changed

## Expected behavior

I'm not sure if this is a bug or just the intended behavior, but I would expect the `onChange` handler to be fired when the time changes even if the input is not complete, so to say.

## Actual behavior

Just the `onClose` handler is called. The `onChange` handler only is called when also picking the minutes (together with `onAccept`).

**Comment by oliviertassinari** [comment] 2020-06-15 13:14
Duplicate of #1709

**Closed as completed by oliviertassinari** 2020-06-15 13:14 UTC
Labels: duplicate, component: DateTimePicker
