### ISSUE TITLE
DateRangePicker. Unable to override Day Component

### ISSUE THREAD

**Issue by michsee** [mui-org/material-ui-pickers#1722] opened 2020-04-29 11:43 UTC
There is no ability to override Day Component in DateRangePicker via `renderDay` props

In source code seems like find the location of the problem
Default renderDay always override our passed prop renderDay 

```
<Calendar
        {...other}
        date={date}
        onChange={onChange}
        renderDay={(day, _, DayProps) => (
          <DateRangeDay
            isPreviewing={false}
            isStartOfPreviewing={false}
            isEndOfPreviewing={false}
            isHighlighting={isWithinRange(utils, day, date)}
            isStartOfHighlighting={isStartOfRange(utils, day, date)}
            isEndOfHighlighting={isEndOfRange(utils, day, date)}
            {...DayProps}
          />
        )}
      />

```

**Comment by dmtrKovalenko** [comment] 2020-04-29 11:44
Really. Thanks its a pitfall XD

**Comment by michsee** [comment] 2020-04-29 11:52
> Really. Thanks its a pitfall XD

Will be fixed in the next release? :)

**Comment by oscar-b** [comment] 2020-05-14 07:59
@dmtrKovalenko Is it enough to move `{...other}` to the end, or do you think that will cause other problems? I could whip up a PR for that otherwise.

**Comment by dmtrKovalenko** [comment] 2020-05-14 08:02
We need to pass DateRangeProps. All of these isHighlighting props

**Comment by oliviertassinari** [comment] 2020-06-15 15:09
Duplicate of #1856

**Closed as completed by oliviertassinari** 2020-06-15 15:10 UTC
Labels: duplicate

**Comment by bneigher** [comment] 2020-06-16 23:00
@oliviertassinari why is this closed?
