### ISSUE TITLE
[docs] Remove "props not recognized by the pickers are not passed down to material-ui TextField"

### ISSUE THREAD

**Issue by stunaz** [mui-org/material-ui-pickers#1837] opened 2020-05-29 04:24 UTC
## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers | 4.0.0-alpha.7        |
| material-ui          |  latest       |
| TypeScript           | latest         |
| React                |  latest        |
| Peer library         |  dayjs       |  |

## Steps to reproduce

I thought I could do the following :
```typescript
            <DatePicker
                label="Basic example"
                variant="outlined"
                value={selectedDate}
                onChange={(date: any) => handleDateChange(date)}
                renderInput={(muiProps) => <TextField {...muiProps} />}
            />
```
`muiProps` does not have the `variant` prop, although the docs says:

> Any prop not recognized by the pickers and their sub-components are passed down to material-ui TextField component.

I know I could/(probably should) pass the `variant` prop on the `renderInput`, but the docs says I could use it on `DatePicker` and it will passed down to `TextField ` as it is not a `DatePicker` prop.

## Expected behavior

`TextField` props  passed to `DatePicker` should passed down to the render props.

## Actual behavior

1. typescript complains that `variant` does not match type
2. `variant` is not passed down to the render props.

and other questons
why is not `renderInput={(muiProps) => <TextField {...muiProps} />}` the default behaviour ?

**Comment by dmtrKovalenko** [comment] 2020-05-29 06:20
Yes, thanks we need to remove it.

**Comment by oliviertassinari** [comment] 2020-05-29 08:16
Duplicate of #1792

**Comment by oliviertassinari** [comment] 2020-05-29 08:21
Actually, I think that we can handle the documentation issue here. @stunaz What do you think of this diff?

```diff
diff --git a/docs/pages/api/props.tsx b/docs/pages/api/props.tsx
index c0a3b966..34e865f0 100644
--- a/docs/pages/api/props.tsx
+++ b/docs/pages/api/props.tsx
@@ -44,20 +44,6 @@ const Docs: React.FC<WithRouterProps> = ({ router }) => {
       <h4> Import </h4>
       <Code language="jsx">{`import { ${componentName} } from '@material-ui/pickers'`}</Code>

-      <h4> Inheritance </h4>
-      <Typography gutterBottom>
-        Any prop not recognized by the pickers and their sub-components are passed down to
-        material-ui{' '}
-        <a
-          target="_blank"
-          rel="noopener noreferer"
-          href="https://material-ui.com/api/text-field/#props"
-        >
-          TextField
-        </a>{' '}
-        component.
-      </Typography>
-
       <Typography gutterBottom>
         <code>DateIOType</code> — date object type of your linked date-io adapter (Moment, DayJS,
         etc.)
```

Do you want to work on it? :)

**Closed as completed** 2020-05-29 23:56 UTC
Labels: good first issue, docs
