### ISSUE TITLE
Setting minutesStep should automatically generate errors for invalid typed minutes

### ISSUE THREAD

**Issue by dandv** [mui-org/material-ui-pickers#1826] opened 2020-05-25 10:19 UTC
**Is your feature request related to a problem? Please describe.**
If `minutesStep` is set, users can type a time that's not divisible by the number of minutes.

**Describe the solution you'd like**
The component should highlight such times as errors.

**Describe alternatives you've considered**
I've [handled the error in `onChange`](https://codesandbox.io/s/mui-v4-datetimepicker-with-rhf-jqv1c?file=/index.tsx:1577-1924) but I didn't know how to set the `.Mui-error` class on the `TextField`.

**Additional context**
[Demo CSB](https://codesandbox.io/s/material-keyboarddatetimepicker-minutestep-should-generate-error-for-invalid-times-9jv5x?file=/index.tsx) with v4.

**Comment by dmtrKovalenko** [comment] 2020-05-25 10:24
Duplicate of #1151

**Closed as completed** 2020-05-25 10:24 UTC
Labels: duplicate
