### ISSUE TITLE
onChange does not follow the normal event handling design pattern

### ISSUE THREAD

**Issue by FoxyWolfy** [mui-org/material-ui-pickers#1407] opened 2019-11-26 21:46 UTC
| Tech                           | Version |
| ----------------------- | ------- |
| @material-ui/pickers | v3.2.8  |

onChange does not follow normal event handling design pattern.  Please provide the original DOM event to onChange.

o  Always provide the event as the first argument to any user facing event prop handler
o  The "event.target" needs to be supplied
o  The "event.target.name" should be the control name
o  The "event.target.value" should contain the "date"

What's not obvious is where the date originated from. Without the event a complex app doesn't have the originating "event.target" and therefore cannot determine the originating control with "event.target.name". 

All we get is a "date". From which control?  We have multiple modules with dozens of controls that send changes up to a parent. This is the only control that doesn't forward the event on an onChange. 

We cannot use material-ui-pickers until onChange supports the established event handling design pattern

**Comment by dmtrKovalenko** [comment] 2019-11-26 22:18
Duplicate of tons of issues

**Closed as completed** 2019-11-26 22:17 UTC

**Comment by FoxyWolfy** [comment] 2019-11-27 00:54
Aren't you suppose to link this issue to the duplicate issue?  
Just closing issues as you are doing displays extremely poor development methodology.

**Comment by dmtrKovalenko** [comment] 2019-11-27 03:04
Only issues that was found super fast, there are more #182, #473, #483, #644, #974. Please try to search through the currently closed issues before opening new one
