### ISSUE TITLE
As a User i would like to pick a single Day as Daterange in the DateRangePicker

### ISSUE THREAD

**Issue by mlasy** [mui-org/material-ui-pickers#1970] opened 2020-07-10 15:20 UTC
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-pickers/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

Currently, picking a single day in the DateRangepicker resulsts in an Error [invalidRange, invalidRange].

## Motivation 🔦
My client rents out his vehicles also for singleday use.

**Comment by oliviertassinari** [comment] 2020-07-10 20:56
Duplicate of #1759

**Closed as completed by oliviertassinari** 2020-07-10 20:56 UTC
Labels: duplicate, component: DateRangePicker
