### ISSUE TITLE
DateRangePicker should have a prop to allow single day date ranges

### ISSUE THREAD

**Issue by Jdban** [mui-org/material-ui-pickers#1968] opened 2020-07-09 23:42 UTC
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-pickers/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

We're using the DateRangePicker to select date ranges, but sometimes the user will want to select just a single day. We should be allowed to set a prop for whether that option is allowed or not.

## Examples 🌈

This is the current behavior when a single day is chosen for the date range
![image](https://user-images.githubusercontent.com/490005/87101084-f71fc900-c202-11ea-9488-9285d800d9f7.png)

We would love a prop to allow this to not be shown as an error.

**Comment by oliviertassinari** [comment] 2020-07-09 23:45
Duplicate of #1759

**Closed as completed by oliviertassinari** 2020-07-09 23:45 UTC
Labels: duplicate, component: DateRangePicker
