### ISSUE TITLE
DateRangePicker issues in a Popover

### ISSUE THREAD

**Issue by ggascoigne** [mui-org/material-ui-pickers#1947] opened 2020-07-01 23:38 UTC
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-pickers/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

We've been trying to use the DateRangePicker in a Popover and have issues with the control closing prematurely.

Pretty much any click in the control causes it to close, this means that you can't navigate months, and if you click on a start date the control closes and you have to reopen it to select the end date.

Based on some other issues we tried displaying the form in a Popper, for the DateRangePicker that did work, but it makes Select controls unusable.  Any click on them causes the containing Popper to close.

This is a desktop and not a mobile use case.

## Expected Behavior 🤔

Some popup like behavior should work with both Select and DateRangePicker at the same time.

## Steps to Reproduce 🕹

Here's a simple example that shows both behaviors: https://codesandbox.io/s/github/ggascoigne/date-picker-bug

The Popover has a Select that works and a DateRangePicker that doesn't, the Popper has a working DateRangePicker and a broken Select.

## Context 🔦

We have a popup that displays a number of filtering fields that are then applied to a table.  The popup is pretty transient, with filters applied onBlur and on return.

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| @material-ui/core | v4.11.0  |
| @material-ui/pickers | v4.0.0-alpha.8  |

Note that I tried this same example with a local build of the latest 6a09d98daf61021beb9b9a56ad4a0c0f0a904cdc version and it appears  to have the same behavior, which is a bit odd, I'd have expected that https://github.com/mui-org/material-ui-pickers/pull/1850 might have effected this.

**Comment by oliviertassinari** [comment] 2020-07-02 08:47
Duplicate of #1852

**Closed as completed by oliviertassinari** 2020-07-02 08:47 UTC
Labels: duplicate, component: DateRangePicker
