### ISSUE TITLE
unexpected selected day in calendar when value={null}

### ISSUE THREAD

**Issue by kerosan** [mui-org/material-ui-pickers#1820] opened 2020-05-25 08:02 UTC
| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |"^4.9.11"|
| material-ui          |"^4.0.0-alpha.7"|

## Expected behavior
clear calendar without selected days

## Actual behavior
by default selected today date

https://codesandbox.io/s/nice-brattain-0g5lt?file=/src/App.jsx

**Comment by dmtrKovalenko** [comment] 2020-05-25 10:30
Duplicate of #1204

**Closed as completed** 2020-05-25 10:29 UTC
Labels: duplicate
