### ISSUE TITLE
Way to disable specific times

### ISSUE THREAD

**Issue by amosyuen** [mui-org/material-ui-pickers#1334] opened 2019-09-30 04:40 UTC
![A GIF or MEME to give some spice of the internet](url)

**Is your feature request related to a problem? Please describe.**

`shouldDisableDate` works for disabling choosing specific days. But there is no equivalent for disabling specific times (e.g. only allow between 8am - 11pm, and 3pm - 6pm)

**Describe the solution you'd like**

You could also use `shouldDisableDate` for disabling times, or add a new `shouldDisableTime` property.

**Describe alternatives you've considered**

**Additional context**

**Comment by dmtrKovalenko** [comment] 2019-10-08 16:24
Duplicate of #519

**Closed as completed by dmtrKovalenko** 2019-10-08 16:24 UTC
