### ISSUE TITLE
RangeError: Format string contains an unescaped latin alphabet character `n`

### ISSUE THREAD

**Issue by iameldj** [mui-org/material-ui-pickers#1729] opened 2020-04-30 18:46 UTC
HOW CAN I SOLVE THIS ISSUE. THANKS

![A GIF or MEME to give some spice of the internet](url)

## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |         |
| material-ui          |         |
| TypeScript           |         |
| React                |         |
| Browser              |         |
| Peer library         |         |  |

## Steps to reproduce

1. 2. 3.

## Live example

<!--
 Live examples help us to investigate bugs and save our time.
 Please try to make this example as simple as possible.
 To create an example you can fork this playground:
 https://codesandbox.io/s/o7oojx

**Comment by dmtrKovalenko** [comment] 2020-04-30 18:53
Duplicate of #1440

**Closed as completed by dmtrKovalenko** 2020-04-30 18:53 UTC
Labels: duplicate
