### ISSUE TITLE
DateRangePicker issue when rendered inside a Modal

### ISSUE THREAD

**Issue by neokike** [mui-org/material-ui-pickers#1777] opened 2020-05-16 02:16 UTC
## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |  v4.0.0-alpha7       |
| material-ui          |   v4.9.11      |
| React                | v16.13.1        |
| Peer library         |  date-fns       |  |

## Steps to reproduce

1. render the DateRangePicker inside a Dialog
2. click on the start input
3. select a date from the calendar

## Expected behavior

the picker calendar popup should stay open when selecting the start date

## Actual behavior

the picker calendar popup close when start date is selected

## Live example

https://codesandbox.io/s/range-picker-issue-f9g99?file=/index.js

**Comment by oliviertassinari** [comment] 2020-05-16 12:57
@neokike Duplicate of https://github.com/mui-org/material-ui/issues/15694

**Closed as completed by oliviertassinari** 2020-05-16 12:57 UTC
Labels: duplicate, component: DateRangePicker
