### ISSUE TITLE
Validation display at keydown but give feedback at blur

### ISSUE THREAD

**Issue by tgaeta** [mui-org/material-ui-pickers#1325] opened 2019-09-23 21:12 UTC
## Environment

| Tech                           | Version |
| --------------------  | ------- |
| @material-ui/pickers | 2.2.4 |
| material-ui                 | core@3.4.0 |
| React                         | 16.8.6 |
| Browser                     | Firefox Quantum v.69 |

## Steps to reproduce

Wire up a datepicker and a submit button. The submit button should have a disabled field. When the datepicker has an error, the submit button isn't disabled until I click out of the datepicker; even though the datepicker itself shows an error.

## Expected behavior
Expected behavior should be as soon as an error happens, I should be allowed to update the state of whatever I want, not have to wait for an onBlur event or the focus to change.

## Actual behavior

When I input an invalid character, I get an immediate error from the datepicker, but I can't piggyback off that to update the state of a button. I've tried using `onError` on the component, but I cannot update the state of my button to disabled until after the focus is moved from the datepicker.

## Live example

![onError](https://user-images.githubusercontent.com/9040988/65462386-b7c6ee00-de23-11e9-8415-c9763daa4366.gif)

**Comment by dmtrKovalenko** [comment] 2020-04-13 08:09
I think it will be fixed by #1426

**Closed as completed by dmtrKovalenko** 2020-04-13 08:09 UTC
Labels: status: incomplete

**Comment by oliviertassinari** [comment] 2020-04-13 09:48
@dmtrKovalenko I don't think that the issue is related to the popup. Looking at the screenshot, the problem seems to be that the UI only takes the error into account on the blur event, not the key event. This lead to an inconsistency in the UI.

I have tried to reproduce with:

- v3: https://codesandbox.io/s/damp-cache-cnul8?file=/src/App.js:0-875
- v4: https://codesandbox.io/s/interesting-star-n3m6b?file=/src/App.js.

No issue. This lead me to believe that the root issue is in @tgaeta's codebase or in v2. I think that it's a good example that we should be aggressively closing issues that don't provide reproduction or using an older version of the library (below v4). Unless we can quickly see what could go wrong.
