### ISSUE TITLE
Feature Request: Ability to select a date and time range

### ISSUE THREAD

**Issue by aeroxy** [mui-org/material-ui-pickers#1779] opened 2020-05-16 18:55 UTC
Amazing work on the recently released date range feature. It would be great if we can also add the ability to select time range as well. (For example May 17th 12:45 pm to May 17th 8:00pm)

**Comment by oliviertassinari** [comment] 2020-05-18 21:25
Duplicate of #1636

**Closed as completed by oliviertassinari** 2020-05-18 21:25 UTC
Labels: duplicate
