### ISSUE TITLE
Time picker: grey out minutes not divisible by minuteStep

### ISSUE THREAD

**Issue by dandv** [mui-org/material-ui-pickers#1811] opened 2020-05-24 08:16 UTC
![image](https://user-images.githubusercontent.com/33569/82749128-f4087080-9d5b-11ea-8142-d0fcf1dd0f80.png)

**Is your feature request related to a problem? Please describe.**
I want to enable users to select meeting times that can only be 00, 15, 30, or 45, so I'm using `minutesStep={15}`.

**Describe the solution you'd like**
Grey out minutes not divisible by 15. Otherwise it's not clear to the user why they can't select them.

![image](https://user-images.githubusercontent.com/33569/82749078-b1df2f00-9d5b-11ea-9f55-8982ac4ac688.png)

**Comment by oliviertassinari** [comment] 2020-05-24 11:53
Duplicate of #1151.

**Closed as completed** 2020-05-24 11:55 UTC
Labels: duplicate, component: TimePicker
