### ISSUE TITLE
ShouldDisableDate not triggered if views = {["year", "month"]}

### ISSUE THREAD

**Issue by ieltxualganaras** [mui-org/material-ui-pickers#1368] opened 2019-10-28 16:29 UTC
## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |    3.2.7    |
| material-ui          |    4.5     |
| React                |    16.10     |
| Browser              |    Chrome     |
| Peer library         |     Moment  1.3.11  |  |

## Steps to reproduce

1. set attribute views to {["year", "month"]}
2. implement shouldDisableDate
3. Open modal

## Expected behavior

I would like to disable the entire month if all the days of that month are disabled.

## Actual behavior

Can't disable the dates for that month because shouldDisableDate its not triggered

**Comment by dmtrKovalenko** [comment] 2020-04-13 08:07
Duplicate of #1002

**Closed as completed by dmtrKovalenko** 2020-04-13 08:07 UTC
Labels: duplicate
