### ISSUE TITLE
Format string contains an unescaped latin alphabet character `n`

### ISSUE THREAD

**Issue by drtobbyas** [mui-org/material-ui-pickers#1463] opened 2020-01-20 10:29 UTC
Material-UI pickers (@material-ui/pickers) popping error 'Format string contains an unescaped latin alphabet character `n`'

- [ x] The issue is present in the latest release.
- [x ] I have searched the [issues](https://github.com/mui-org/material-ui/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

it's popping error 'Format string contains an unescaped latin alphabet character `n`'
## Expected Behavior 🤔
suppose to display date picker

fix
## Steps to Reproduce 🕹
initialize a new react project in codesandbox, copy the first documentation example on material-ui date picker section

Steps:

1.
2.
3.
4.

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Material-UI | v4.8.3  |
| React       |         |
| Browser     |         |
| TypeScript  |         |
| etc.        |         |

**Comment by oliviertassinari** [comment] 2020-01-20 11:08
It's a duplicate of #1440.

**Closed as completed by oliviertassinari** 2020-01-20 11:08 UTC
