### ISSUE TITLE
Alternative time picker UI

### ISSUE THREAD

**Issue by ElyDotDev** [mui-org/material-ui-pickers#2042] opened 2020-07-27 12:58 UTC
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-pickers/issues) of this repository and believe that this is not a duplicate.

## Summary 💡
Add alternative time picker UI rather than `ClockView`, or add the ability to pass a component to be used instead of `ClockView`, like `ToolbarComponent` prop.

## Examples 🌈

Clock view: 
![image](https://user-images.githubusercontent.com/13997186/88543784-bbbc3180-d02d-11ea-90f0-f91654cf29a8.png)

Custom (needed) view:
![image](https://user-images.githubusercontent.com/13997186/88544412-95e35c80-d02e-11ea-9111-f241fe7cc2ff.png)

## Motivation 🔦
Currently, the time picker UI uses `ClockView` component, which is part of the material design. But, working with the clock is not straightforward as it looks, and I got lots of negative feedback from my customers and user. I created my own time-picker. It works. But I want to ask is it possible to add an alternative time picker UI, like the above picture, or add the prop? I can work on the new picker UI and send a PR.

**Comment by dmtrKovalenko** [comment] 2020-07-27 13:00
Duplicate of mui/material-ui#1860

**Comment by oliviertassinari** [comment] 2020-07-27 13:00
@alirdn Are you targeting desktop of mobile? If desktop, it's a duplicate of mui/material-ui#1860, if mobile, it's a new concern.

**Closed as completed** 2020-07-27 13:00 UTC
Labels: duplicate

**Comment by ianpavlovski** [comment] 2021-01-23 21:53
this is not a duplicate!

**Comment by oliviertassinari** [comment] 2021-01-23 22:09
See https://github.com/mui-org/material-ui/issues/23690
