### ISSUE TITLE
Override dialog action button color won't work

### ISSUE THREAD

**Issue by Typhon0** [mui-org/material-ui-pickers#1376] opened 2019-10-30 15:29 UTC
![A GIF or MEME to give some spice of the internet](http://giphygifs.s3.amazonaws.com/media/aZ3LDBs1ExsE8/giphy.gif)

## Environment

| Tech                 | Version |
| -------------------- | ------- |
| @material-ui/pickers |  3.2.7  |
| material-ui          |  4.5.2  |
| React                | 16.11.0 |
| Browser              | Chronium (78.0.3905.1) |

## Bug

I try to override the dialog action button color but material UI tells me that dialogAction does not exist.

````   
 MuiPickersModal: {
      dialogAction: {
        color: '#86bc25',
      },
    },
````
Warning in the console:
````
Material-UI: you are trying to override a style that does not exist.
Fix the `dialogAction` key of `theme.overrides.MuiPickersModal`.
````

**Comment by yanickrochon** [comment] 2019-12-16 20:23
Just installed everything, still this issue.

* `@material-ui/core`: 4.8.0
* `@material-ui/pickers`: 3.2.8

## Update

I solved this with

```
    overrides: {
      MuiButton: {
        textPrimary: {
          color: '#80d8ff',
        }
      },
    }
``` 

+1 for some broken docs!

**Comment by oliviertassinari** [comment] 2020-03-31 14:50
Duplicate of #1356

**Closed as completed by oliviertassinari** 2020-03-31 14:50 UTC
Labels: duplicate
